"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../../lib/api";
type Tx=any;
const money=(x:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(x||0));
export default function TransactionsPage(){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[q,setQ]=useState(""),[kind,setKind]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const [offset,setOffset]=useState(0); const limit=25;
 async function load(nextOffset=offset){setBusy(true);setError(null);try{const p=new URLSearchParams({limit:String(limit),offset:String(nextOffset)});if(q)p.set("q",q);if(kind)p.set("order_kind",kind);if(status)p.set("order_status",status);const r=await apiFetch<{data:any}>("/api/v1/admin/control-plane/transactions?"+p.toString());setData(r.data);setOffset(nextOffset)}catch(e){setError(e instanceof Error?e.message:"TRANSACTIONS_LOAD_FAILED")}finally{setBusy(false)}}
 useEffect(()=>{void load(0)},[kind,status]);
 async function detail(id:string){setError(null);try{const r=await apiFetch<{data:any}>("/api/v1/admin/control-plane/transactions/"+id);setSelected(r.data)}catch(e){setError(e instanceof Error?e.message:"TRANSACTION_DETAIL_FAILED")}}
 const items:Tx[]=data?.items??[]; const total=Number(data?.total??0);
 return <main className="min-h-screen p-6 sm:p-10"><div className="mx-auto max-w-[1700px]">
  <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.24em] text-cyan-300">Allpha Control Plane · Phase 27C</p><h1 className="mt-3 text-4xl font-semibold">Transaction Explorer</h1><p className="mt-3 text-slate-400">Orders, payment attempts, Midtrans references, items, buyers/sellers and operational history from the source of truth.</p></div><a href="/overview" className="rounded-xl border border-white/10 px-4 py-2 text-sm">Overview</a></div>
  <section className="mt-8 grid gap-3 md:grid-cols-[1fr_180px_180px_auto]"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load(0)}} placeholder="Order ID, username, provider reference…" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3"/><select value={kind} onChange={e=>setKind(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3"><option value="">All order kinds</option><option value="marketplace">Marketplace</option><option value="credit_purchase">Credit purchase</option><option value="subscription">Subscription</option><option value="booth">Booth</option><option value="live">Live</option><option value="other">Other</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3"><option value="">All statuses</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="failed">Failed</option></select><button onClick={()=>void load(0)} className="rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950">Search</button></section>
  {error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm">{error}</div>}
  <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-white/10 text-left text-xs text-slate-500"><tr><th className="px-5 py-4">Order</th><th>Buyer</th><th>Kind</th><th>Amount</th><th>Payment</th><th>Provider</th><th>Created</th><th></th></tr></thead><tbody>{items.length===0?<tr><td colSpan={8} className="px-5 py-12 text-center text-slate-500">{busy?"Loading…":"No authoritative transactions found."}</td></tr>:items.map((x:any)=><tr key={x.order_id} className="border-t border-white/5"><td className="px-5 py-4"><div className="font-mono text-xs">{x.order_id}</div><div className="mt-1 text-slate-500">{x.order_status}</div></td><td>{x.buyer_display_name||x.buyer_username||x.buyer_user_id}</td><td>{x.order_kind}</td><td>{money(x.total_amount)}<div className="text-xs text-slate-500">{x.item_count} item</div></td><td>{x.payments?.[0]?.status||"—"}</td><td>{x.payments?.[0]?.provider_transaction_id||x.payments?.[0]?.external_reference||"—"}</td><td className="text-xs text-slate-500">{new Date(x.created_at).toLocaleString("id-ID")}</td><td><button onClick={()=>void detail(x.order_id)} className="rounded-lg border border-cyan-300/30 px-3 py-2 text-xs">Open</button></td></tr>)}</tbody></table></div>
   <div className="flex items-center justify-between border-t border-white/10 p-4 text-sm text-slate-400"><span>{total} total</span><div className="flex gap-2"><button disabled={offset===0||busy} onClick={()=>void load(Math.max(0,offset-limit))} className="rounded-lg border border-white/10 px-3 py-2 disabled:opacity-30">Previous</button><button disabled={offset+limit>=total||busy} onClick={()=>void load(offset+limit)} className="rounded-lg border border-white/10 px-3 py-2 disabled:opacity-30">Next</button></div></div>
  </section>
  {selected&&<div className="fixed inset-0 z-50 bg-black/70 p-4 sm:p-10" onClick={()=>setSelected(null)}><div className="mx-auto max-h-full max-w-6xl overflow-auto rounded-2xl border border-white/10 bg-slate-950 p-6" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Transaction Drill-down</h2><button onClick={()=>setSelected(null)} className="rounded-lg border border-white/10 px-3 py-2">Close</button></div><pre className="mt-6 whitespace-pre-wrap break-words rounded-xl border border-white/10 bg-black/20 p-4 text-xs text-slate-300">{JSON.stringify(selected,null,2)}</pre></div></div>}
 </div></main>
}