"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../../lib/api";
type Credit={id:string;name:string;description:string|null;credits:number;price_amount:number;currency:string};
type Plan={id:string;name:string;description:string|null;interval_unit:string;interval_count:number;price_amount:number;currency:string;included_credits:number};
type Summary={credit_balance:number;active_subscription:{id:string;plan_id:string;status:string;current_period_start:string;current_period_end:string}|null};
const money=(n:number,c:string)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:c,maximumFractionDigits:0}).format(n);
export default function EconomyPage(){
 const [credits,setCredits]=useState<Credit[]>([]),[plans,setPlans]=useState<Plan[]>([]),[summary,setSummary]=useState<Summary|null>(null),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");
 async function load(){try{const [c,p,s]=await Promise.all([apiFetch<{data:Credit[]}>("/api/v1/economy/credit-products"),apiFetch<{data:Plan[]}>("/api/v1/billing/plans"),apiFetch<Summary>("/api/v1/economy/summary")]);setCredits(c.data||[]);setPlans(p.data||[]);setSummary(s)}catch(e){setMessage(e instanceof Error?e.message:"Economy unavailable")}}
 useEffect(()=>{void load()},[]);
 async function buyCredit(id:string){try{setBusy(id);const r=await apiFetch<{redirect_url:string}>(`/api/v1/economy/credit-products/${id}/purchase`,{method:"POST",body:JSON.stringify({idempotency_key:crypto.randomUUID()})});window.location.assign(r.redirect_url)}catch(e){setMessage(e instanceof Error?e.message:"Credit checkout failed")}finally{setBusy(null)}}
 async function subscribe(id:string){try{setBusy(id);const r=await apiFetch<{redirect_url:string}>(`/api/v1/billing/plans/${id}/subscribe`,{method:"POST",body:JSON.stringify({idempotency_key:crypto.randomUUID()})});window.location.assign(r.redirect_url)}catch(e){setMessage(e instanceof Error?e.message:"Subscription checkout failed")}finally{setBusy(null)}}
 return <main className="mx-auto max-w-7xl space-y-8 p-6 text-[var(--allpha-text)]"><header><p className="text-xs uppercase tracking-[.22em] text-[var(--allpha-cyan)]">Phase 25</p><h1 className="mt-2 text-4xl font-semibold">Economy, Credits & Billing</h1><p className="mt-3 max-w-3xl text-sm text-white/60">Allpha uses one centralized payment boundary. Credit purchases, subscriptions, and Marketplace Commerce are checked out through Midtrans from the Allpha Web App.</p></header>{message&&<div className="rounded-xl border border-white/10 p-3 text-sm">{message}</div>}<section className="rounded-2xl border border-white/10 bg-[var(--allpha-surface)] p-5"><p className="text-xs uppercase tracking-wider text-white/40">AI Credits</p><div className="mt-2 text-4xl font-semibold">{summary?.credit_balance??0}</div><p className="text-sm text-white/50">Current posted balance</p></section><section><h2 className="text-2xl font-semibold">Credit Packages</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{credits.length===0?<p className="text-sm text-white/50">No published credit packages are configured yet.</p>:credits.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-[var(--allpha-surface)] p-5"><h3 className="text-xl font-medium">{x.name}</h3><p className="mt-2 text-sm text-white/60">{x.description||(`${x.credits} AI Credits`)}</p><div className="mt-5 flex items-center justify-between"><div><b>{x.credits}</b><span className="ml-1 text-sm text-white/40">credits</span><div className="text-sm text-white/50">{money(x.price_amount,x.currency)}</div></div><button disabled={busy===x.id} onClick={()=>void buyCredit(x.id)} className="rounded-lg bg-[var(--allpha-cyan)] px-4 py-2 text-sm font-semibold text-black">{busy===x.id?"Opening…":"Buy"}</button></div></article>)}</div></section><section><h2 className="text-2xl font-semibold">Plans</h2><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{plans.length===0?<p className="text-sm text-white/50">No published billing plans are configured yet.</p>:plans.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-[var(--allpha-surface)] p-5"><h3 className="text-xl font-medium">{x.name}</h3><p className="mt-2 text-sm text-white/60">{x.description||"Allpha subscription plan"}</p><p className="mt-4 text-2xl font-semibold">{money(x.price_amount,x.currency)}<span className="text-sm text-white/40"> / {x.interval_count} {x.interval_unit}</span></p><p className="mt-2 text-sm text-white/50">{x.included_credits} included AI credits</p><button disabled={busy===x.id||!!summary?.active_subscription} onClick={()=>void subscribe(x.id)} className="mt-5 w-full rounded-lg border border-white/10 px-4 py-2 text-sm">{summary?.active_subscription?"Subscription active":busy===x.id?"Opening…":"Subscribe with Midtrans"}</button></article>)}</div></section></main>
}