"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../../lib/api";
export default function Page(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(""),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<any|null>(null);
 async function load(){setError(null);try{const r=await apiFetch<{data:any[]}>("/api/v1/admin/agent-authority/audit-logs?limit=200");setRows((r.data??[]).filter((x:any)=>!q||JSON.stringify(x).toLowerCase().includes(q.toLowerCase())))}catch(e){setError(e instanceof Error?e.message:"ADMIN_AUDIT_LOAD_FAILED")}}
 useEffect(()=>{void load()},[]);
 return <main className="min-h-screen p-6 sm:p-10"><div className="mx-auto max-w-[1600px]"><p className="text-xs uppercase tracking-[0.24em] text-cyan-300">Trust · Phase 27D</p><h1 className="mt-3 text-4xl font-semibold">Audit Evidence</h1><p className="mt-3 max-w-4xl text-slate-400">Read-only evidence from the canonical audit ledger. This surface never creates audit fixtures.</p>
 <div className="mt-8 flex gap-3"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Filter action, resource, actor…" className="flex-1 rounded-xl border border-white/10 bg-white/5 px-4 py-3"/><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-4 py-3">Refresh</button></div>
 {error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-sm">{error}</div>}
 <section className="mt-6 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-white/10 text-left text-xs text-slate-500"><tr><th className="px-5 py-4">Time</th><th>Action</th><th>Resource</th><th>Outcome</th><th>Actor</th><th></th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={6} className="px-5 py-12 text-center text-slate-500">No authoritative audit records returned.</td></tr>:rows.map((x:any)=><tr key={x.id} className="border-t border-white/5"><td className="px-5 py-4 text-xs text-slate-500">{x.created_at?new Date(x.created_at).toLocaleString("id-ID"):"—"}</td><td>{x.action??"—"}</td><td>{x.resource_type??"—"}</td><td>{x.outcome??"—"}</td><td className="font-mono text-xs">{x.actor_user_id??x.actor_id??"system"}</td><td><button onClick={()=>setSelected(x)} className="rounded-lg border border-cyan-300/30 px-3 py-2 text-xs">Evidence</button></td></tr>)}</tbody></table></div></section>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onClick={()=>setSelected(null)}><section className="max-h-[85vh] w-full max-w-3xl overflow-auto rounded-2xl border border-white/10 bg-slate-950 p-6" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">Audit evidence</h2><button onClick={()=>setSelected(null)} className="rounded-lg border border-white/10 px-3 py-2">Close</button></div><pre className="mt-5 rounded-xl border border-white/10 bg-white/[0.03] p-4 text-xs text-slate-300">{JSON.stringify(selected,null,2)}</pre></section></div>}
 </div></main>;
}