"use client";
import { useEffect, useState } from "react";
import { apiFetch } from "../../lib/api";
type ConfigVersion={id:string;namespace:string;version_no:number;status:"draft"|"published"|"archived";created_at:string;published_at:string|null};
export default function ConfigVersionsPage(){
 const [items,setItems]=useState<ConfigVersion[]>([]),[namespace,setNamespace]=useState(""),[configText,setConfigText]=useState("{}"),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 async function load(){setError(null);try{const r=await apiFetch<{data:ConfigVersion[]}>("/api/v1/admin/control-plane/config-versions");setItems(r.data??[])}catch(e){setError(e instanceof Error?e.message:"CONFIG_VERSIONS_LOAD_FAILED")}}
 useEffect(()=>{void load()},[]);
 async function createDraft(){setBusy(true);setError(null);try{const config=JSON.parse(configText) as Record<string,unknown>;await apiFetch("/api/v1/admin/control-plane/config-versions",{method:"POST",body:JSON.stringify({namespace,config})});setNamespace("");setConfigText("{}");await load()}catch(e){setError(e instanceof Error?e.message:"CONFIG_VERSION_CREATE_FAILED")}finally{setBusy(false)}}
 async function publish(id:string){setBusy(true);setError(null);try{await apiFetch("/api/v1/admin/control-plane/config-versions/"+id+"/publish",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"CONFIG_VERSION_PUBLISH_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-6 sm:p-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-medium uppercase tracking-[0.24em] text-cyan-300">Phase 27A · Governance</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Configuration Versions</h1><p className="mt-3 max-w-3xl text-slate-400">Versioned configuration with explicit draft → publish lifecycle. Publishing is server-authoritative and audited.</p>{error?<div className="mt-5 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm">{error}</div>:null}<section className="mt-8 rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="font-semibold">Create draft</h2><div className="mt-4 grid gap-4"><input value={namespace} onChange={e=>setNamespace(e.target.value)} placeholder="namespace.example" className="rounded-xl border border-white/10 bg-white/5 px-4 py-3"/><textarea value={configText} onChange={e=>setConfigText(e.target.value)} rows={8} spellCheck={false} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 font-mono text-sm"/></div><button disabled={!namespace||busy} onClick={()=>void createDraft()} className="mt-4 rounded-xl bg-cyan-300 px-4 py-3 font-semibold text-slate-950 disabled:opacity-40">{busy?"Saving…":"Create draft"}</button></section><section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">{items.length===0?<p className="p-6 text-sm text-slate-400">No configuration versions exist.</p>:<div className="divide-y divide-white/10">{items.map(item=><div key={item.id} className="flex flex-wrap items-start justify-between gap-4 p-5"><div><p className="font-medium">{item.namespace} · v{item.version_no}</p><p className="mt-1 text-xs uppercase tracking-wider text-slate-500">{item.status}</p></div><div>{item.status==="draft"?<button disabled={busy} onClick={()=>void publish(item.id)} className="rounded-lg border border-cyan-300/40 px-3 py-2 text-xs">Publish</button>:null}</div></div>)}</div>}</section></div></main>;
}