"use client";
import {useEffect,useState} from "react";
import {apiFetch} from "../../lib/api";
type D=any;
const groups=[["roles","RBAC Roles"],["permissions","Permissions"],["agent_types","Agent Types"],["agent_skills","Agent Skills"],["agent_characters","Agent Characters"],["themes","Themes"],["theme_versions","Theme Versions"],["world_templates","World Templates"],["billing_plans","Billing Plans"],["credit_products","Credit Products"],["ai_providers","AI Providers"],["ai_models","AI Models"],["feature_flags","Feature Flags"],["config_versions","Config Versions"]];
export default function MasterDataPage(){
 const [d,setD]=useState<D|null>(null),[active,setActive]=useState("roles"),[err,setErr]=useState<string|null>(null);
 useEffect(()=>{void apiFetch<{data:D}>("/api/v1/admin/control-plane/master-data").then(x=>setD(x.data)).catch(e=>setErr(e instanceof Error?e.message:"ADMIN_MASTER_DATA_FAILED"))},[]);
 const rows=d?.[active]??[];
 return <main className="min-h-screen p-6 sm:p-10"><div className="mx-auto max-w-[1600px]"><p className="text-xs uppercase tracking-[0.24em] text-cyan-300">Allpha Control Plane · Phase 27B</p><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="mt-3 text-4xl font-semibold">Master Data</h1><p className="mt-3 text-slate-400">Authoritative catalogs and platform configuration. Sensitive provider credentials are intentionally excluded.</p></div><a href="/analytics" className="rounded-xl border border-white/10 px-4 py-2 text-sm">Analytics</a></div>{err&&<div className="mt-6 rounded-2xl border border-red-400/20 bg-red-400/10 p-4">{err}</div>}<div className="mt-8 flex gap-2 overflow-x-auto pb-2">{groups.map(([key,label])=><button key={key} onClick={()=>setActive(key)} className={`whitespace-nowrap rounded-xl border px-4 py-2 text-sm ${active===key?"border-cyan-300/60 bg-cyan-300/10":"border-white/10"}`}>{label} <span className="text-slate-500">{d?.[key]?.length??0}</span></button>)}</div><section className="mt-4 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b border-white/10 text-left text-xs text-slate-500"><tr><th className="px-5 py-4">Key / Name</th><th className="px-5 py-4">Category / Status</th><th className="px-5 py-4">Details</th><th className="px-5 py-4">State</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={4} className="px-5 py-10 text-center text-slate-500">No authoritative records in this catalog.</td></tr>:rows.map((x:any,i:number)=><tr key={x.id??i} className="border-b border-white/5"><td className="px-5 py-4"><div className="font-medium">{x.name??x.display_name??x.key??x.slug??x.model_key??x.provider_key??x.namespace??"—"}</div><div className="font-mono text-[11px] text-slate-600">{x.id??x.key??x.slug??""}</div></td><td className="px-5 py-4 text-slate-400">{x.category??x.status??x.archetype??x.adapter??x.interval_unit??"—"}</td><td className="max-w-xl px-5 py-4 text-slate-400">{x.description??x.model_identifier??x.character_key??x.plan_key??x.product_key??x.skill_key??x.type_key??x.catalog_key??x.namespace??"—"}</td><td className="px-5 py-4">{x.enabled!==undefined?(x.enabled?"Enabled":"Disabled"):(x.moderation_status??x.status??x.validation_status??"—")}</td></tr>)}</tbody></table></div></section></div></main>