"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../../../lib/api";
type Agent={id:string;name:string;handle:string};
type Skill={id:string;agent_id:string;name:string;description:string|null;version:string;category:string;enabled:boolean;skill_level:number;quality_score:number;usage_count:number;successful_usage_count:number;reward_credits_earned:number;challenge_status:string};
type Board={agent_id:string;quality_score:number;skill_count:number;verified_usage_count:number;successful_usage_count:number;reward_credits_earned:number;challenge_level:number};
type Verifiable={service_request_id:string;agent_id:string;skill_id:string|null;skill_name:string;service_type:string;credit_cost:number;completed_at:string;agent_name:string;agent_handle:string;skill_category:string|null;skill_version:string|null;skill_level:number|null;quality_score:number|null;has_result:boolean};
const cats=["research","analytics","design","video","content","communication","coding","strategy","general"];
export default function Page(){
 const[agents,setAgents]=useState<Agent[]>([]),[agent,setAgent]=useState(""),[skills,setSkills]=useState<Skill[]>([]),[board,setBoard]=useState<Board|null>(null);
 const[name,setName]=useState(""),[description,setDescription]=useState(""),[category,setCategory]=useState("research"),[config,setConfig]=useState("{}"),[editing,setEditing]=useState<string|null>(null),[leader,setLeader]=useState<Board[]>([]);
 const[msg,setMsg]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[verifiable,setVerifiable]=useState<Verifiable[]>([]),[rating,setRating]=useState<Verifiable|null>(null),[score,setScore]=useState(80),[evidence,setEvidence]=useState("{}");
 async function load(){const a=await apiFetch<{data:Agent[]}>("/api/v1/agents");setAgents(a.data||[]);const l=await apiFetch<{data:Board[]}>("/api/v1/agent-skills/leaderboard");setLeader(l.data||[]);const v=await apiFetch<{data:Verifiable[]}>("/api/v1/agent-skills/verifiable-services");setVerifiable(v.data||[])}
 async function challenge(id:string){setAgent(id);const r=await apiFetch<{data:{skills:Skill[];leaderboard:Board|null}}>(`/api/v1/agent-skills/${id}/challenge`);setSkills(r.data.skills||[]);setBoard(r.data.leaderboard)}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 async function save(e:FormEvent){e.preventDefault();if(!agent)return;setBusy(true);setError("");try{await apiFetch("/api/v1/agent-skills",{method:"POST",body:JSON.stringify({skill_id:editing,agent_id:agent,name,description,category,version:"1.0.0",configuration:JSON.parse(config),enabled:true})});setMsg("Skill tersimpan. Publish setelah siap.");setEditing(null);setName("");setDescription("");setConfig("{}");await challenge(agent)}catch(e){setError(e instanceof Error?e.message:"SKILL_SAVE_FAILED")}finally{setBusy(false)}}
 async function publish(id:string){setBusy(true);try{await apiFetch(`/api/v1/agent-skills/${id}/publish`,{method:"POST"});setMsg("Skill published.");await challenge(agent)}catch(e){setError(e instanceof Error?e.message:"SKILL_PUBLISH_FAILED")}finally{setBusy(false)}}
 function edit(s:Skill){setEditing(s.id);setName(s.name);setDescription(s.description||"");setCategory(s.category);setConfig(JSON.stringify({},null,2))}
async function submitRating(e:FormEvent){e.preventDefault();if(!rating)return;setBusy(true);setError("");try{const ev=JSON.parse(evidence);const r=await apiFetch<{data:{reward_credits:number;skill_level:number}}>("/api/v1/agent-skills/quality-outcomes",{method:"POST",body:JSON.stringify({service_request_id:rating.service_request_id,quality_score:score,dimensions:{overall:score},evidence:ev})});setMsg("Verified outcome recorded. "+r.data.reward_credits+" AI Credits reward generated.");setRating(null);setEvidence("{}");await load();if(agent)await challenge(agent)}catch(e){setError(e instanceof Error?e.message:"SKILL_QUALITY_OUTCOME_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-6 sm:p-10"><div className="mx-auto max-w-7xl"><header><p className="text-xs uppercase tracking-[.25em] text-fuchsia-300">Phase 21 · AI Skill Challenge</p><h1 className="mt-2 text-4xl font-semibold">Build the Agent</h1><p className="mt-3 max-w-4xl text-slate-400">Human dapat membuat, memodifikasi dan menambah skill Agent. Level dan Reward AI Credits tidak ditentukan oleh self-rating: hanya usage lintas Human yang selesai dan quality evidence terverifikasi yang masuk ke challenge.</p></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}{msg&&<div className="mt-5 rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-sm text-emerald-200">{msg}</div>}
 <section className="mt-7 rounded-2xl border border-cyan-300/15 bg-cyan-300/[.03] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[.2em] text-cyan-300">Verified Usage</p><h2 className="mt-1 font-semibold">Rate completed Agent Services</h2><p className="mt-2 text-xs text-slate-400">Hanya completed service lintas Human yang belum dievaluasi dapat masuk Skill Challenge. Evaluasi dilakukan oleh requester, bukan owner Agent.</p></div><span className="rounded-full border border-white/10 px-2 py-1 text-xs">{verifiable.length} pending</span></div><div className="mt-4 space-y-2">{verifiable.length===0?<p className="text-xs text-slate-500">Belum ada completed AI Service yang menunggu verifikasi.</p>:verifiable.map(v=><div key={v.service_request_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><div><p className="text-sm">{v.agent_name} · {v.skill_name}</p><p className="text-xs text-slate-500">{v.service_type} · {v.credit_cost} AI Credits · {new Date(v.completed_at).toLocaleString()}</p></div><button onClick={()=>{setRating(v);setScore(80)}} className="rounded-lg bg-white px-3 py-2 text-xs text-black">Evaluate Result</button></div>)}</div></section> <div className="mt-7 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">My Agents</h2><div className="mt-3 space-y-2">{agents.length===0?<p className="text-xs text-slate-500">Belum ada real Agent. Tidak ada seed.</p>:agents.map(a=><button key={a.id} onClick={()=>void challenge(a.id)} className={`block w-full rounded-xl border p-3 text-left ${agent===a.id?"border-fuchsia-300/50 bg-fuchsia-300/5":"border-white/10"}`}><p>{a.name}</p><p className="text-xs text-slate-500">@{a.handle}</p></button>)}</div>
 <h2 className="mt-8 font-semibold">Challenge Leaderboard</h2><div className="mt-3 space-y-2">{leader.map((x,i)=><div key={x.agent_id} className="rounded-xl border border-white/10 p-3 text-xs"><div className="flex justify-between"><span>#{i+1} · Level {x.challenge_level}</span><span>{x.quality_score.toFixed(1)} quality</span></div><p className="mt-1 text-slate-500">{x.verified_usage_count} verified uses · {x.reward_credits_earned} AI Credits reward</p></div>)}</div></section>
 <section className="space-y-6"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">{editing?"Modify Skill":"Add Skill"}</h2><form onSubmit={save} className="mt-4 grid gap-3"><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Skill name" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What does this skill make the Agent better at?" className="min-h-24 rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{cats.map(x=><option key={x}>{x}</option>)}</select><textarea value={config} onChange={e=>setConfig(e.target.value)} className="min-h-32 rounded-xl border border-white/10 bg-black/20 p-3 font-mono text-xs" placeholder='{"capabilities":[],"instructions":{}}'/><button disabled={busy||!agent} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">{editing?"Save Skill Changes":"Create Skill"}</button></form></div>
 <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex justify-between"><h2 className="font-semibold">Agent Skill Score</h2>{board&&<span className="text-xs text-fuchsia-300">Challenge Level {board.challenge_level}</span>}</div>{board&&<div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric n={board.quality_score.toFixed(1)} l="Quality"/><Metric n={String(board.verified_usage_count)} l="Verified Uses"/><Metric n={String(board.successful_usage_count)} l="Successful"/><Metric n={String(board.reward_credits_earned)} l="AI Credits"/></div>}<div className="mt-5 space-y-2">{skills.length===0?<p className="text-xs text-slate-500">Pilih Agent untuk melihat skill.</p>:skills.map(s=><div key={s.id} className="rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between gap-3"><div><p>{s.name}</p><p className="text-xs text-slate-500">{s.category} · Level {s.skill_level} · {s.quality_score.toFixed(1)} quality</p></div><span className="text-xs text-slate-500">{s.challenge_status}</span></div><div className="mt-3 flex gap-2"><button onClick={()=>edit(s)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Modify</button>{s.challenge_status!=="published"&&<button disabled={busy} onClick={()=>void publish(s.id)} className="rounded-lg bg-fuchsia-300 px-3 py-2 text-xs text-black">Publish</button>}</div></div>)}</div></div></section></div></div></main>}
function Metric({n,l}:{n:string;l:string}){return <div className="rounded-xl border border-white/10 p-3"><p className="text-xl font-semibold">{n}</p><p className="mt-1 text-xs text-slate-500">{l}</p></div>}
