"use client";
import type { ButtonHTMLAttributes, HTMLAttributes, ReactNode } from "react";
type Tone="neutral"|"primary"|"cyan"|"violet"|"success"|"warning"|"danger";
const toneClass:Record<Tone,string>={neutral:"allpha-tone-neutral",primary:"allpha-tone-primary",cyan:"allpha-tone-cyan",violet:"allpha-tone-violet",success:"allpha-tone-success",warning:"allpha-tone-warning",danger:"allpha-tone-danger"};
export function cx(...values:Array<string|false|null|undefined>){return values.filter(Boolean).join(" ")}
export function GlassSurface({children,className,as:Tag="div",...props}:HTMLAttributes<HTMLElement>&{as?:"div"|"section"|"article"|"aside";children:ReactNode}){return <Tag className={cx("allpha-surface",className)} {...props}>{children}</Tag>}
export function UniverseButton({children,variant="secondary",tone="primary",className,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"ghost"|"icon";tone?:Tone}){return <button className={cx("allpha-button",`allpha-button-${variant}`,toneClass[tone],variant==="icon"&&"allpha-button-icon",className)} {...props}>{children}</button>}
export function SpatialNode({children,tone="primary",className,...props}:HTMLAttributes<HTMLDivElement>&{tone?:Tone;children:ReactNode}){return <div className={cx("allpha-node",toneClass[tone],className)} {...props}><span className="allpha-node-orbit" aria-hidden="true"/><span className="allpha-node-core" aria-hidden="true"/><span className="allpha-node-content">{children}</span></div>}
export function ContentCapsule({eyebrow,title,description,children,className,...props}:HTMLAttributes<HTMLElement>&{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <article className={cx("allpha-capsule",className)} {...props}><div className="allpha-capsule-meta">{eyebrow?<span className="allpha-eyebrow">{eyebrow}</span>:null}<span className="allpha-capsule-signal" aria-hidden="true"/></div><h3>{title}</h3>{description?<p>{description}</p>:null}{children?<div className="allpha-capsule-actions">{children}</div>:null}</article>}
export function ContextSheet({children,className,...props}:HTMLAttributes<HTMLDivElement>&{children:ReactNode}){return <div className={cx("allpha-context-sheet",className)} {...props}><span className="allpha-sheet-handle" aria-hidden="true"/>{children}</div>}
export function StatusOrb({label,tone="success",className}:{label:string;tone?:Tone;className?:string}){return <span className={cx("allpha-status",className)}><span className={cx("allpha-status-dot",toneClass[tone])} aria-hidden="true"/>{label}</span>}

export function GlassChip({children,active=false,className,...props}:HTMLAttributes<HTMLSpanElement>&{active?:boolean;children:ReactNode}){return <span className={cx("allpha-ui-chip",active&&"is-active",className)} aria-current={active?"true":undefined} {...props}>{children}</span>}
export function SectionHeading({eyebrow,title,description,action,className,...props}:{eyebrow?:string;title:string;description?:string;action?:ReactNode;className?:string}&HTMLAttributes<HTMLElement>){return <header className={cx("allpha-ui-section-header",className)} {...props}><div>{eyebrow?<span className="allpha-ui-eyebrow">{eyebrow}</span>:null}<h2>{title}</h2>{description?<p>{description}</p>:null}</div>{action?<div className="allpha-ui-section-action">{action}</div>:null}</header>}
export function IconButton({label,children,className,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string;children:ReactNode}){return <button type="button" aria-label={label} title={label} className={cx("allpha-ui-icon-button",className)} {...props}>{children}</button>}
export function StatusBadge({children,tone="neutral",className,...props}:{children:ReactNode;tone?:Tone;className?:string}&HTMLAttributes<HTMLSpanElement>){return <span className={cx("allpha-ui-status-badge",`tone-${tone}`,className)} {...props}>{children}</span>}
