from __future__ import annotations

from fastapi import APIRouter, Depends

from app.api.dependencies import require_permission

router = APIRouter(
    prefix="/api/v1/admin/domain-evidence",
    tags=["Admin Domain Evidence"],
)

# This registry is an evidence surface, not a second domain engine.
# Each entry points to an existing canonical engine/table/API/UI surface.
# Runtime/provider gates remain explicit and are never inferred as GREEN.
DOMAIN_EVIDENCE = [
    {
        "domain": "Stories Engine",
        "status": "PARTIAL",
        "canonical_engine": "Content + Live",
        "db": ["content_items", "content_media", "content_events", "live_sessions"],
        "rpc": ["create_content", "publish_content", "record_content_event"],
        "api": ["/api/v1/content", "/api/v1/live"],
        "ui": ["Content surfaces", "Live surfaces"],
        "gap": "No story-specific persistence/contract was found; story semantics remain content/live composed.",
        "runtime_gate": True,
    },
    {
        "domain": "Trend Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Feed + Social + Analytics",
        "db": ["content_events", "feed_interaction_events", "social_activity_events", "ai_usage_events"],
        "rpc": ["record_content_event", "record_ai_usage_event", "get_admin_analytics"],
        "api": ["/api/v1/feed", "/api/v1/discovery", "/api/v1/admin/control-plane/analytics"],
        "ui": ["Feed", "Discovery", "Admin Analytics"],
        "gap": "Trend ranking is derived from canonical telemetry; no duplicate trend store is required.",
        "runtime_gate": True,
    },
    {
        "domain": "Creator Economy",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Commerce + Payout + Reputation",
        "db": ["commerce_orders", "commerce_order_items", "payout_requests", "payout_events", "agent_reputation_events"],
        "rpc": ["get_admin_payout_requests", "get_admin_transaction_explorer"],
        "api": ["/api/v1/marketplace", "/api/v1/payouts", "/api/v1/admin/control-plane/payouts"],
        "ui": ["Marketplace", "Payouts", "Admin Transactions"],
        "gap": "Creator earnings are derived from canonical commerce/settlement/payout records; no second creator ledger.",
        "runtime_gate": True,
    },
    {
        "domain": "Event Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Community Engine + Live + Notification",
        "db": ["community_events", "community_event_attendees", "community_activity_events"],
        "rpc": ["create_community_event", "rsvp_community_event"],
        "api": ["/api/v1/communities/{community_id}/events"],
        "ui": ["Community events"],
        "gap": "Event lifecycle is canonically owned by Community; no duplicate Event engine.",
        "runtime_gate": True,
    },
    {
        "domain": "Tenant Leasing & Billing",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Booth/Tenant + Commerce + Billing",
        "db": ["booths", "booth_leases", "billing_invoices", "billing_subscriptions", "commerce_orders"],
        "rpc": ["request_booth_lease", "activate_booth_lease"],
        "api": ["/api/v1/booths", "/api/v1/economy", "/api/v1/admin/control-plane"],
        "ui": ["Booths", "Billing", "Admin Operations"],
        "gap": "Lease is a canonical booth/commerce lifecycle; billing remains canonical Billing/Economy.",
        "runtime_gate": True,
    },
    {
        "domain": "Theme Marketplace",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Theme Engine + Marketplace + Moderation",
        "db": ["themes", "theme_versions", "theme_assets", "marketplace_listings", "marketplace_offers"],
        "rpc": ["create_theme", "publish_theme", "create_marketplace_listing", "publish_marketplace_listing"],
        "api": ["/api/v1/themes", "/api/v1/marketplace"],
        "ui": ["Theme Builder/Catalog", "Marketplace", "Admin Themes"],
        "gap": "Theme assets and marketplace are separate canonical engines; listing ownership/commerce remains Marketplace.",
        "runtime_gate": True,
    },
    {
        "domain": "Agent Simulation Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Spatial Runtime",
        "db": ["simulation_sessions", "simulation_ticks", "agent_spatial_states", "spatial_runtime_events"],
        "rpc": ["start_world_simulation", "advance_world_simulation_tick", "record_simulation_tick"],
        "api": ["/api/v1/spatial-runtime"],
        "ui": ["World/Spatial surfaces"],
        "gap": "Simulation engine exists at source level; active Agent simulation requires real Agent runtime activation.",
        "runtime_gate": True,
    },
    {
        "domain": "Encounter Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Presence + Spatial Interaction + Agent Context",
        "db": ["spatial_interactions", "agent_spatial_states", "spatial_runtime_events", "universe_agent_presences"],
        "rpc": ["update_agent_spatial_state", "upsert_universe_agent_presence"],
        "api": ["/api/v1/spatial-runtime", "/api/v1/universe"],
        "ui": ["Universe/World surfaces"],
        "gap": "Encounter semantics are derived from canonical spatial/presence interactions; no duplicate encounter store.",
        "runtime_gate": True,
    },
    {
        "domain": "Presence Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Spatial Runtime + Realtime",
        "db": ["agent_spatial_states", "universe_agent_presences", "live_human_presence_verifications"],
        "rpc": ["upsert_universe_agent_presence", "exit_universe_agent_presence"],
        "api": ["/api/v1/universe", "/api/v1/spatial-runtime"],
        "ui": ["Universe/World/Live"],
        "gap": "Presence source exists; authenticated realtime presence is a runtime gate.",
        "runtime_gate": True,
    },
    {
        "domain": "Realtime World Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Spatial Runtime + Supabase Realtime",
        "db": ["spatial_runtime_events", "district_activity_events", "booth_activity_events", "agent_runtime_events"],
        "rpc": ["record_simulation_tick", "update_agent_spatial_state"],
        "api": ["/api/v1/spatial-runtime", "/api/v1/live"],
        "ui": ["World/Live surfaces"],
        "gap": "Realtime publication/configuration exists; authenticated subscription behavior remains runtime-gated.",
        "runtime_gate": True,
    },
    {
        "domain": "World Stream",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Universe + Content + Feed",
        "db": ["universe_world_content", "universe_worlds", "content_items", "feed_impressions", "feed_interaction_events"],
        "rpc": ["link_universe_world_content", "record_content_event"],
        "api": ["/api/v1/universe", "/api/v1/feed", "/api/v1/discovery"],
        "ui": ["Universe", "Feed", "Discovery"],
        "gap": "World stream is a composed stream; no duplicate world-stream database is required.",
        "runtime_gate": True,
    },
    {
        "domain": "Identity Verification",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Identity + Security + Live",
        "db": ["identities", "profiles", "security_devices", "live_human_presence_verifications"],
        "rpc": ["get_agent_authority_snapshot"],
        "api": ["/api/v1/identity", "/api/v1/security", "/api/v1/live"],
        "ui": ["Identity/Security", "Live"],
        "gap": "Verification evidence is distributed across identity/security/live contracts; real verification requires authenticated runtime.",
        "runtime_gate": True,
    },
    {
        "domain": "Anti-Impersonation",
        "status": "FOUNDATION",
        "canonical_engine": "Identity Verification + Agent Identity + Security",
        "db": ["identities", "agent_identities", "security_events", "audit_logs"],
        "rpc": ["get_agent_authority_snapshot", "refresh_agent_passport"],
        "api": ["/api/v1/identity", "/api/v1/security"],
        "ui": ["Identity/Security"],
        "gap": "No dedicated anti-impersonation policy/evidence contract was found; must be closed before security GREEN.",
        "runtime_gate": True,
    },
    {
        "domain": "Anti-Fraud",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Risk + Commerce + Security + Audit",
        "db": ["risk_assessments", "commerce_events", "economy_settlement_events", "security_events", "audit_logs"],
        "rpc": ["get_admin_transaction_governance_context", "record_agent_spend"],
        "api": ["/api/v1/security", "/api/v1/economy", "/api/v1/admin/control-plane"],
        "ui": ["Admin Risk", "Security", "Transactions"],
        "gap": "Fraud controls are composed from canonical Risk/Commerce/Security; provider/payment runtime remains gated.",
        "runtime_gate": True,
    },
    {
        "domain": "Agent Interoperability",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Agent Identity + Discovery + Messaging + Collaboration",
        "db": ["agent_identities", "agent_passports", "agent_collaboration_requests", "agent_collaboration_agreements", "messages"],
        "rpc": ["discover_collaboration_agents", "create_agent_collaboration_request", "get_agent_collaboration_history"],
        "api": ["/api/v1/agent-collaboration", "/api/v1/messaging"],
        "ui": ["Agent Collaboration", "Messaging"],
        "gap": "Cross-owner interoperability is owned by Collaboration/Messaging; external protocol interoperability is not yet runtime-proven.",
        "runtime_gate": True,
    },
    {
        "domain": "Agent API / Protocol",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "API Contract + Agent Runtime + Tool Registry",
        "db": ["agent_tool_definitions", "agent_tool_runs", "agent_credentials", "agent_execution_contexts"],
        "rpc": ["create_agent_command", "begin_agent_execution", "record_agent_tool_result"],
        "api": ["/api/v1/agent-runtime", "/api/v1/ai-gateway"],
        "ui": ["Agent/Runtime surfaces"],
        "gap": "Internal protocol/tool execution is source-connected; external developer protocol compatibility is not runtime-proven.",
        "runtime_gate": True,
    },
    {
        "domain": "Revenue Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Commerce + Billing + Payout",
        "db": ["commerce_orders", "commerce_payments", "economy_settlement_events", "payout_requests", "payout_events", "billing_invoices"],
        "rpc": ["get_admin_transaction_explorer", "get_admin_payout_requests"],
        "api": ["/api/v1/economy", "/api/v1/payouts", "/api/v1/admin/control-plane"],
        "ui": ["Billing", "Payouts", "Admin Transactions"],
        "gap": "Revenue is derived from canonical settlement/payout/billing state; no duplicate revenue ledger.",
        "runtime_gate": True,
    },
    {
        "domain": "Developer Platform",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Agent API + Tool Registry + Credentials + AI Gateway",
        "db": ["agent_tool_definitions", "agent_tool_runs", "agent_credentials", "ai_models", "ai_providers"],
        "rpc": ["begin_agent_execution", "record_agent_tool_result"],
        "api": ["/api/v1/agent-runtime", "/api/v1/ai-gateway"],
        "ui": ["Agent/Runtime surfaces"],
        "gap": "Developer primitives exist; public developer onboarding/API-key lifecycle is not yet a production/runtime contract.",
        "runtime_gate": True,
    },
    {
        "domain": "Evaluation Engine",
        "status": "IMPLEMENTED FOUNDATION",
        "canonical_engine": "Agent Skills + Runtime Outcomes + Reviews + Telemetry",
        "db": ["agent_skill_challenge_events", "agent_skill_challenge_leaderboard", "agent_skills", "agent_collaboration_reviews", "ai_usage_events"],
        "rpc": ["record_agent_skill_quality_outcome", "submit_agent_collaboration_review", "get_admin_analytics"],
        "api": ["/api/v1/agent-skills", "/api/v1/agent-collaboration", "/api/v1/admin/control-plane/analytics"],
        "ui": ["Agent Skills", "Collaboration", "Admin Analytics"],
        "gap": "Evaluation evidence is source-connected; statistically meaningful runtime evaluation requires real traffic.",
        "runtime_gate": True,
    },
    {
        "domain": "E2E Test / QA Engine",
        "status": "FOUNDATION",
        "canonical_engine": "Repository test suite + deployment/runtime gates",
        "db": ["audit_logs", "security_events", "ai_usage_events", "commerce_events", "workflow_events"],
        "rpc": [],
        "api": ["/api/v1/health", "canonical domain routers"],
        "ui": ["PWA/Admin"],
        "gap": "E2E QA cannot be declared complete before credentials, authenticated browser/API execution, CI, staging and production gates.",
        "runtime_gate": True,
    },
]


@router.get("")
async def domain_evidence(
    context: dict = Depends(require_permission("admin.read")),
) -> dict:
    return {
        "data": {
            "generated_at": "source-registry",
            "registry_version": "20261004.1",
            "note": "Source-level evidence registry only; runtime/provider gates remain explicit.",
            "domains": DOMAIN_EVIDENCE,
        }
    }
