"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../../lib/api";

type District={id:string;name:string;status:string}; type Zone={id:string;name:string;zone_key:string}; type Booth={id:string;name:string;slug:string;tier:string;status:string;moderation_status:string;district_id:string;district_zone_id:string|null;theme_key:string|null}; type Asset={id:string;status:string;asset_type:string;storage_path:string;content_size_bytes:number|null;uploaded_at:string|null};
export default function Page(){
 const[districts,setDistricts]=useState<District[]>([]),[zones,setZones]=useState<Zone[]>([]),[booths,setBooths]=useState<Booth[]>([]),[districtId,setDistrictId]=useState(""),[zoneId,setZoneId]=useState("");
 const[name,setName]=useState(""),[slug,setSlug]=useState(""),[tier,setTier]=useState("free"),[type,setType]=useState("personal"),[themeKey,setThemeKey]=useState(""),[selectedBoothId,setSelectedBoothId]=useState(""),[assets,setAssets]=useState<Asset[]>([]),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null);
 async function loadDistricts(){try{const r=await apiFetch<{data:District[]}>("/api/v1/districts");setDistricts(r.data||[])}catch(e){setError(e instanceof Error?e.message:"DISTRICT_LOAD_FAILED")}}
 async function loadZones(id:string){setDistrictId(id);setZoneId("");if(!id){setZones([]);return}try{const r=await apiFetch<{data:Zone[]}>("/api/v1/districts/"+id+"/zones");setZones(r.data||[])}catch(e){setError(e instanceof Error?e.message:"ZONE_LOAD_FAILED")}}
 async function loadBooths(){try{const r=await apiFetch<{data:Booth[]}>(districtId?"/api/v1/booths?district_id="+encodeURIComponent(districtId):"/api/v1/booths");setBooths(r.data||[])}catch(e){setError(e instanceof Error?e.message:"BOOTH_LOAD_FAILED")}}
 useEffect(()=>{void loadDistricts();void loadBooths()},[]); useEffect(()=>{if(districtId)void loadBooths()},[districtId]);
 async function loadAssets(id:string){setSelectedBoothId(id);setAssets([]);try{const r=await apiFetch<{data:Asset[]}>(`/api/v1/booths/${id}/assets/3d`);setAssets(r.data||[])}catch(e){setError(e instanceof Error?e.message:"BOOTH_3D_ASSET_LOAD_FAILED")}} async function upload3d(){if(!selectedBoothId||!file)return;if(!file.name.toLowerCase().endsWith(".glb")){setError("ONLY_GLB_SUPPORTED");return}setBusy(true);setError(null);setMessage(null);try{const prepared=await apiFetch<{data:{asset:Asset;upload:{signed_url:string}}}>(`/api/v1/booths/${selectedBoothId}/assets/3d/upload-url`,{method:"POST"});const upload=await fetch(prepared.data.upload.signed_url,{method:"PUT",headers:{"Content-Type":"model/gltf-binary","x-upsert":"false"},body:file});if(!upload.ok)throw new Error("STORAGE_UPLOAD_FAILED");await apiFetch(`/api/v1/booths/${selectedBoothId}/assets/${prepared.data.asset.id}/3d/finalize`,{method:"POST"});setFile(null);setMessage("3D asset tersimpan dan tervalidasi dari Storage.");await loadAssets(selectedBoothId)}catch(e){setError(e instanceof Error?e.message:"BOOTH_3D_UPLOAD_FAILED")}finally{setBusy(false)}} async function create(e:FormEvent){e.preventDefault();setBusy(true);setError(null);setMessage(null);try{await apiFetch("/api/v1/booths",{method:"POST",body:JSON.stringify({district_id:districtId,district_zone_id:zoneId||null,booth_type:type,tier,name,slug,theme_key:themeKey||null,display_config:{presentation_only:true},scene_config:{presentation_only:true},catalog_config:{},live_entry_config:{}})});setName("");setSlug("");await loadBooths()}catch(e){setError(e instanceof Error?e.message:"BOOTH_CREATE_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl"><header><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 20</p><h1 className="mt-2 text-4xl font-semibold">Booth / Tenant</h1><p className="mt-3 max-w-3xl text-slate-400">Create real Human, Agent, Creator or Business spaces inside an existing District and Zone. Persistence goes through FastAPI → Supabase; no synthetic records.</p></header>{error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}{message&&<div className="mt-5 rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-sm text-emerald-200">{message}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Provision Booth</h2><form onSubmit={create} className="mt-4 grid gap-3"><select value={districtId} onChange={e=>void loadZones(e.target.value)} required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">Select existing District</option>{districts.map(d=><option key={d.id} value={d.id}>{d.name} · {d.status}</option>)}</select><select value={zoneId} onChange={e=>setZoneId(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">No Zone / District-level</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name} · {z.zone_key}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Booth name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="booth-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><div className="grid grid-cols-2 gap-3"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["personal","creator","agent","business","store","office","studio","community_space","event_venue","collaboration_space"].map(x=><option key={x}>{x}</option>)}</select><select value={tier} onChange={e=>setTier(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["free","standard","creator","business","prime","event","enterprise"].map(x=><option key={x}>{x}</option>)}</select></div><input value={themeKey} onChange={e=>setThemeKey(e.target.value)} placeholder="Optional Theme catalog key" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><button disabled={busy||!districtId} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Create Booth</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex justify-between"><h2 className="font-semibold">Authoritative Booths</h2><button onClick={()=>void loadBooths()} className="text-xs text-slate-400">Refresh</button></div>{booths.length===0?<p className="mt-5 text-sm text-slate-500">No real Booth/Tenant records yet.</p>:<div className="mt-5 space-y-2">{booths.map(b=><button type="button" onClick={()=>void loadAssets(b.id)} key={b.id} className={`block w-full rounded-xl border p-4 text-left ${selectedBoothId===b.id?"border-cyan-300/50 bg-cyan-300/5":"border-white/10"}`}><div className="flex justify-between gap-3"><span>{b.name}</span><span className="text-xs uppercase text-slate-500">{b.status}</span></div><p className="mt-1 text-xs text-slate-500">{b.tier} · {b.moderation_status} · {b.theme_key||"No theme"}</p><p className="mt-1 break-all text-[11px] text-slate-600">{b.id}</p></div>)}</div>}</section></div></div></main>;
}