"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { apiFetch } from "../../lib/api";
import AgentAccountCard, { AgentAccount } from "../../components/agent-account-card";

type District={id:string;name:string;status:string};
type Zone={id:string;name:string;zone_key:string;status:string};
type Booth={id:string;name:string;slug:string;tier:string;booth_type:string;status:string;moderation_status:string;district_id:string;district_zone_id:string|null;theme_key:string|null;host_agent_id:string|null;display_config?:Record<string,unknown>;scene_config?:Record<string,unknown>;catalog_config?:Record<string,unknown>;live_entry_config?:Record<string,unknown>;branding_config?:Record<string,unknown>;portal_config?:Record<string,unknown>};
type Asset={id:string;status:string;asset_type:string;storage_path:string;content_size_bytes:number|null;uploaded_at:string|null;signed_url?:string};
type Lease={id:string;tier:string;size_class:string;visibility_class:string;traffic_score:number|null;price_amount:number|null;currency:string|null;billing_cycle:string|null;starts_at:string;ends_at:string|null;status:string};\ntype Slot={id:string;slot_key:string;asset_id:string|null;presentation_config:Record<string,unknown>};

const types=["personal","creator","agent","business","store","office","studio","community_space","event_venue","collaboration_space"];
const tiers=["free","standard","creator","business","prime","event","enterprise"];

function jsonOrEmpty(value:string){try{return value.trim()?JSON.parse(value):{};}catch{throw new Error("INVALID_JSON_CONFIG");}}

export default function Page(){
 const[districts,setDistricts]=useState<District[]>([]),[zones,setZones]=useState<Zone[]>([]),[booths,setBooths]=useState<Booth[]>([]);
 const[districtId,setDistrictId]=useState(""),[zoneId,setZoneId]=useState(""),[selected,setSelected]=useState<Booth|null>(null);
 const[name,setName]=useState(""),[slug,setSlug]=useState(""),[type,setType]=useState("personal"),[tier,setTier]=useState("free"),[themeKey,setThemeKey]=useState("");
 const[hostAgentId,setHostAgentId]=useState(""),[branding,setBranding]=useState("{}"),[scene,setScene]=useState("{}"),[catalog,setCatalog]=useState("{}"),[portal,setPortal]=useState("{}");
 const[assets,setAssets]=useState<Asset[]>([]),[leases,setLeases]=useState<Lease[]>([]),[slots,setSlots]=useState<Slot[]>([]),[file,setFile]=useState<File|null>(null),[hostAgent,setHostAgent]=useState<AgentAccount|null>(null);
 const[leaseSize,setLeaseSize]=useState("standard"),[leaseVisibility,setLeaseVisibility]=useState("standard"),[traffic,setTraffic]=useState(""),[price,setPrice]=useState(""),[currency,setCurrency]=useState("IDR"),[billing,setBilling]=useState("monthly"),[starts,setStarts]=useState(""),[ends,setEnds]=useState("");
 const[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[slotKey,setSlotKey]=useState("hero"),[slotAsset,setSlotAsset]=useState("");

 async function loadDistricts(){const r=await apiFetch<{data:District[]}>("/api/v1/districts");setDistricts(r.data||[])}
 async function loadZones(id:string){setDistrictId(id);setZoneId("");setSelected(null);if(!id){setZones([]);return}const r=await apiFetch<{data:Zone[]}>(`/api/v1/districts/${id}/zones`);setZones(r.data||[])}
 async function loadBooths(){const r=await apiFetch<{data:Booth[]}>(districtId?`/api/v1/booths?district_id=${encodeURIComponent(districtId)}`:"/api/v1/booths");setBooths(r.data||[])}
 async function selectBooth(b:Booth){setSelected(b);setAssets([]);setLeases([]);setSlots([]);setHostAgent(null);try{const [a,l,s]=await Promise.all([apiFetch<{data:Asset[]}>(`/api/v1/booths/${b.id}/assets/3d`),apiFetch<{data:Lease[]}>(`/api/v1/booths/${b.id}/leases`),apiFetch<{data:Slot[]}>(`/api/v1/booths/${b.id}/slots`)]);setAssets(a.data||[]);setLeases(l.data||[]);setSlots(s.data||[]);if(b.host_agent_id){try{const ar=await apiFetch<{data:{agent:{id:string;name:string;handle:string|null;description:string|null;avatar_path:string|null;status:string;runtime_state:string;is_owned_by_viewer:boolean};skills:AgentAccount["skills"];reputation:{quality_score:number;verified_usage_count:number;successful_usage_count:number;reward_credits_earned:number;challenge_level:number}}}>(`/api/v1/agent-catalog/accounts/${b.host_agent_id}`);const x=ar.data;setHostAgent({agent_id:x.agent.id,name:x.agent.name,handle:x.agent.handle,description:x.agent.description,avatar_path:x.agent.avatar_path,status:x.agent.status,runtime_state:x.agent.runtime_state,is_owned_by_viewer:x.agent.is_owned_by_viewer,skills:x.skills,quality_score:x.reputation.quality_score,verified_usage_count:x.reputation.verified_usage_count,successful_usage_count:x.reputation.successful_usage_count,reward_credits_earned:x.reputation.reward_credits_earned,challenge_level:x.reputation.challenge_level})}catch{setHostAgent(null)}}}catch(e){setError(e instanceof Error?e.message:"BOOTH_DETAIL_LOAD_FAILED")}}
 useEffect(()=>{void loadDistricts();void loadBooths().catch(e=>setError(e instanceof Error?e.message:"BOOTH_LOAD_FAILED"))},[]);
 useEffect(()=>{if(districtId)void loadBooths().catch(e=>setError(e instanceof Error?e.message:"BOOTH_LOAD_FAILED"))},[districtId]);

 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError(null);setMessage(null);try{
   const b=await apiFetch<{data:Booth}>("/api/v1/booths",{method:"POST",body:JSON.stringify({
    district_id:districtId,district_zone_id:zoneId||null,booth_type:type,tier,name,slug,theme_key:themeKey||null,
    display_config:{presentation_only:true,branding:jsonOrEmpty(branding)},scene_config:{presentation_only:true,...jsonOrEmpty(scene),...(hostAgentId?{host_agent_id:hostAgentId}: {})},
    catalog_config:jsonOrEmpty(catalog),live_entry_config:{metadata_only:true,portal:jsonOrEmpty(portal)}
   })});
   setMessage("Booth draft berhasil dibuat.");setName("");setSlug("");if(b?.data)await selectBooth(b.data);await loadBooths();
 }catch(e){setError(e instanceof Error?e.message:"BOOTH_CREATE_FAILED")}finally{setBusy(false)}}

 async function updateBooth(){if(!selected)return;setBusy(true);setError(null);try{const r=await apiFetch<{data:Booth}>(`/api/v1/booths/${selected.id}`,{method:"PATCH",body:JSON.stringify({name:selected.name,theme_key:selected.theme_key,display_config:selected.display_config??{},scene_config:selected.scene_config??{},catalog_config:selected.catalog_config??{},live_entry_config:selected.live_entry_config??{},branding_config:selected.branding_config??{},portal_config:selected.portal_config??{},host_agent_id:selected.host_agent_id})});if(r.data)setSelected(r.data);setMessage("Booth configuration updated.");await loadBooths()}catch(e){setError(e instanceof Error?e.message:"BOOTH_UPDATE_FAILED")}finally{setBusy(false)}}\n async function bindSlot(e:FormEvent){e.preventDefault();if(!selected||!slotAsset)return;setBusy(true);setError(null);try{await apiFetch(`/api/v1/booths/${selected.id}/slots`,{method:"POST",body:JSON.stringify({slot_key:slotKey,asset_id:slotAsset,presentation_config:{presentation_only:true}})});setMessage("Display slot bound.");setSlotAsset("");await selectBooth(selected)}catch(e){setError(e instanceof Error?e.message:"BOOTH_SLOT_BIND_FAILED")}finally{setBusy(false)}}\n\n async function transition(path:string,label:string){if(!selected)return;setBusy(true);setError(null);try{const r=await apiFetch<{data:Booth}>(`/api/v1/booths/${selected.id}/${path}`,{method:"POST"});if(r.data)setSelected(r.data);setMessage(label);await loadBooths()}catch(e){setError(e instanceof Error?e.message:"BOOTH_LIFECYCLE_FAILED")}finally{setBusy(false)}}

 async function upload3d(){if(!selected||!file)return;setBusy(true);setError(null);try{
   if(!file.name.toLowerCase().endsWith(".glb"))throw new Error("ONLY_GLB_SUPPORTED");
   const p=await apiFetch<{data:{asset:Asset;upload:{signed_url:string}}}>(`/api/v1/booths/${selected.id}/assets/3d/upload-url`,{method:"POST"});
   const up=await fetch(p.data.upload.signed_url,{method:"PUT",headers:{"Content-Type":"model/gltf-binary","x-upsert":"false"},body:file});
   if(!up.ok)throw new Error("STORAGE_UPLOAD_FAILED");
   await apiFetch(`/api/v1/booths/${selected.id}/assets/${p.data.asset.id}/3d/finalize`,{method:"POST"});
   setFile(null);setMessage("GLB berhasil di-upload, diverifikasi Storage, dan diaktifkan.");await selectBooth(selected);
 }catch(e){setError(e instanceof Error?e.message:"BOOTH_3D_UPLOAD_FAILED")}finally{setBusy(false)}}

 async function requestLease(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError(null);try{
   await apiFetch(`/api/v1/booths/${selected.id}/leases`,{method:"POST",body:JSON.stringify({
    tier:selected.tier,size_class:leaseSize,visibility_class:leaseVisibility,traffic_score:traffic===""?null:Number(traffic),
    price_amount:price===""?null:Number(price),currency:currency||null,billing_cycle:billing||null,starts_at:new Date(starts).toISOString(),ends_at:ends?new Date(ends).toISOString():null,
    metadata:{source:"phase20_booth_builder"}
   })});
   setMessage("Lease request tercatat.");await selectBooth(selected);
 }catch(e){setError(e instanceof Error?e.message:"BOOTH_LEASE_REQUEST_FAILED")}finally{setBusy(false)}}

 async function activateLease(id:string){if(!selected)return;setBusy(true);try{await apiFetch(`/api/v1/booths/leases/${id}/activate`,{method:"POST"});setMessage("Lease diaktifkan.");await selectBooth(selected)}catch(e){setError(e instanceof Error?e.message:"BOOTH_LEASE_ACTIVATE_FAILED")}finally{setBusy(false)}}

 const activeLease=useMemo(()=>leases.find(x=>x.status==="active"),[leases]);

 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl">
  <header><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 20 · Booth / Tenant Platform</p><h1 className="mt-2 text-4xl font-semibold">Booth Builder</h1><p className="mt-3 max-w-4xl text-slate-400">Booth adalah spatial tenant/venue. Identity, branding, theme, scene, catalog references, media, AI Host, Portal, dan Live Entry metadata tersimpan melalui FastAPI → Supabase. Commerce, Review, dan Live runtime tetap milik phase domain masing-masing.</p></header>
  {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
  {message&&<div className="mt-5 rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-sm text-emerald-200">{message}</div>}
  <div className="mt-7 grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
   <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Provision / Configure</h2><form onSubmit={create} className="mt-4 grid gap-3">
    <select value={districtId} onChange={e=>void loadZones(e.target.value)} required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">Select active District</option>{districts.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
    <select value={zoneId} onChange={e=>setZoneId(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">District level</option>{zones.filter(x=>x.status==="active").map(x=><option key={x.id} value={x.id}>{x.name} · {x.zone_key}</option>)}</select>
    <div className="grid grid-cols-2 gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Booth name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="booth-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div>
    <div className="grid grid-cols-2 gap-3"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{types.map(x=><option key={x}>{x}</option>)}</select><select value={tier} onChange={e=>setTier(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{tiers.map(x=><option key={x}>{x}</option>)}</select></div>
    <div className="grid grid-cols-2 gap-3"><input value={themeKey} onChange={e=>setThemeKey(e.target.value)} placeholder="Theme catalog key" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={hostAgentId} onChange={e=>setHostAgentId(e.target.value)} placeholder="Owned AI Host Agent UUID (optional)" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div>
    <div className="grid gap-3 md:grid-cols-2"><textarea value={branding} onChange={e=>setBranding(e.target.value)} placeholder='Branding JSON, e.g. {"logo":"..."}' className="min-h-24 rounded-xl border border-white/10 bg-black/20 p-3 text-xs"/><textarea value={scene} onChange={e=>setScene(e.target.value)} placeholder='Scene JSON' className="min-h-24 rounded-xl border border-white/10 bg-black/20 p-3 text-xs"/><textarea value={catalog} onChange={e=>setCatalog(e.target.value)} placeholder='Catalog references JSON' className="min-h-24 rounded-xl border border-white/10 bg-black/20 p-3 text-xs"/><textarea value={portal} onChange={e=>setPortal(e.target.value)} placeholder='Portal metadata JSON' className="min-h-24 rounded-xl border border-white/10 bg-black/20 p-3 text-xs"/></div>
    <button disabled={busy||!districtId} className="rounded-xl bg-white px-4 py-3 text-sm font-medium text-black disabled:opacity-40">Create Real Booth Draft</button>
   </form></section>
   <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Authoritative Booths</h2><button onClick={()=>void loadBooths()} className="text-xs text-slate-400">Refresh</button></div>
    {booths.length===0?<p className="mt-5 text-sm text-slate-500">Belum ada Booth real. Tidak ada seed/fake data.</p>:<div className="mt-4 space-y-2">{booths.map(b=><button type="button" onClick={()=>void selectBooth(b)} key={b.id} className={`block w-full rounded-xl border p-4 text-left ${selected?.id===b.id?"border-cyan-300/50 bg-cyan-300/5":"border-white/10"}`}><div className="flex justify-between gap-3"><span>{b.name}</span><span className="text-xs uppercase text-slate-500">{b.status}</span></div><p className="mt-1 text-xs text-slate-500">{b.booth_type} · {b.tier} · {b.moderation_status} · {b.theme_key||"No theme"}</p></button>)}</div>}
   </section>
  </div>
  {selected&&<div className="mt-6 grid gap-6 lg:grid-cols-2">
   <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex justify-between"><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">{selected.id}</p></div><div className="flex gap-2">{selected.status==="draft"&&<button disabled={busy} onClick={()=>void transition("submit","Booth submitted for moderation.")} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Submit</button>}{selected.status==="pending_review"&&selected.moderation_status==="approved"&&<button disabled={busy} onClick={()=>void transition("publish","Booth published.")} className="rounded-lg bg-cyan-300 px-3 py-2 text-xs text-black">Publish</button>}</div></div>
    <div className="mt-5 rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-medium">Booth configuration</h3><button disabled={busy} onClick={()=>void updateBooth()} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Save</button></div><p className="mt-2 text-xs text-slate-500">Update tetap melewati RPC authority; renderer hanya presentation.</p></div><div className="mt-5 rounded-xl border border-white/10 p-4 text-sm"><p><span className="text-slate-500">3D chain:</span> Theme Template → Booth 3D Asset → AllphaWorldRenderer</p><p className="mt-2"><span className="text-slate-500">Host:</span> {selected.host_agent_id||"No AI Host bound"}</p><p className="mt-2"><span className="text-slate-500">Live:</span> metadata only; runtime belongs to Phase 22</p></div>
    {hostAgent&&<div className="mt-5"><p className="mb-3 text-xs uppercase tracking-[.2em] text-slate-500">AI Host / Agent Account</p><AgentAccountCard agent={hostAgent} compact discoveryContext={{source_surface:"booth",booth_id:selected.id}} /></div>}\n    <div className="mt-5 rounded-xl border border-white/10 p-4"><h3 className="text-sm font-medium">3D Display Slots</h3><form onSubmit={bindSlot} className="mt-3 grid gap-2 sm:grid-cols-3"><input value={slotKey} onChange={e=>setSlotKey(e.target.value)} placeholder="Slot key" className="rounded-lg border border-white/10 bg-black/20 p-2 text-xs"/><select value={slotAsset} onChange={e=>setSlotAsset(e.target.value)} className="rounded-lg border border-white/10 bg-black/20 p-2 text-xs"><option value="">Select asset</option>{assets.map(a=><option key={a.id} value={a.id}>{a.asset_type} · {a.id.slice(0,8)}</option>)}</select><button disabled={busy||!slotAsset} className="rounded-lg bg-white px-3 py-2 text-xs text-black disabled:opacity-40">Bind Slot</button></form><div className="mt-3 space-y-2">{slots.length===0?<p className="text-xs text-slate-500">No display slots.</p>:slots.map(s=><div key={s.id} className="rounded-lg border border-white/10 p-2 text-xs"><div className="flex justify-between"><span>{s.slot_key}</span><span>{s.asset_id?s.asset_id.slice(0,8):"empty"}</span></div></div>)}</div></div><div className="mt-5"><h3 className="text-sm font-medium">Real GLB assets</h3><div className="mt-3 flex flex-wrap gap-3"><input type="file" accept=".glb,model/gltf-binary" onChange={e=>setFile(e.target.files?.[0]??null)} className="max-w-full text-sm"/><button disabled={busy||!file} onClick={()=>void upload3d()} className="rounded-lg bg-white px-3 py-2 text-xs text-black disabled:opacity-40">Upload GLB</button></div>{assets.length===0?<p className="mt-3 text-xs text-slate-500">No active Booth GLB.</p>:<div className="mt-3 space-y-2">{assets.map(a=><div key={a.id} className="rounded-lg border border-white/10 p-3 text-xs"><div className="flex justify-between"><span>{a.asset_type}</span><span>{a.status}</span></div><p className="mt-1 break-all text-slate-500">{a.storage_path}</p><p className="mt-1 text-slate-600">{a.content_size_bytes??0} bytes · signed runtime URL {a.signed_url?"ready":"not available"}</p></div>)}</div>}</div>
   </section>
   <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Tenant Lease</h2><p className="mt-1 text-xs text-slate-500">Price is configurable; this phase does not introduce billing/economy logic.</p><form onSubmit={requestLease} className="mt-4 grid gap-3"><div className="grid grid-cols-2 gap-3"><input value={leaseSize} onChange={e=>setLeaseSize(e.target.value)} placeholder="Size class" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={leaseVisibility} onChange={e=>setLeaseVisibility(e.target.value)} placeholder="Visibility class" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><div className="grid grid-cols-2 gap-3"><input value={traffic} onChange={e=>setTraffic(e.target.value)} type="number" min="0" max="100" placeholder="Traffic score 0–100" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={price} onChange={e=>setPrice(e.target.value)} type="number" min="0" placeholder="Price" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><div className="grid grid-cols-2 gap-3"><input value={currency} onChange={e=>setCurrency(e.target.value)} placeholder="Currency" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={billing} onChange={e=>setBilling(e.target.value)} placeholder="Billing cycle" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><div className="grid grid-cols-2 gap-3"><input value={starts} onChange={e=>setStarts(e.target.value)} type="datetime-local" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={ends} onChange={e=>setEnds(e.target.value)} type="datetime-local" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><button disabled={busy||!!activeLease} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Request Lease</button></form>
    <div className="mt-5 space-y-2">{leases.length===0?<p className="text-xs text-slate-500">No lease records.</p>:leases.map(l=><div key={l.id} className="rounded-xl border border-white/10 p-3 text-xs"><div className="flex justify-between"><span>{l.status} · {l.tier}</span><span>traffic {l.traffic_score??"—"}</span></div><p className="mt-1 text-slate-500">{l.size_class} · {l.visibility_class} · {l.price_amount??"—"} {l.currency||""} · {l.billing_cycle||"—"}</p>{l.status==="pending"&&<button disabled={busy} onClick={()=>void activateLease(l.id)} className="mt-2 rounded-lg border border-white/10 px-3 py-2">Activate</button>}</div>)}</div>
   </section>
  </div>}
 </div></main>;
}
