begin;
select plan(15);
select has_table('public','feed_impressions','feed impressions exists');
select has_table('public','feed_interaction_events','feed interaction events exists');
select has_table('public','feed_feedback','feed feedback exists');
select is((select relrowsecurity from pg_class where oid='public.feed_impressions'::regclass),true,'impressions RLS');
select is((select relrowsecurity from pg_class where oid='public.feed_interaction_events'::regclass),true,'interaction RLS');
select is((select relrowsecurity from pg_class where oid='public.feed_feedback'::regclass),true,'feedback RLS');
select has_function('public','get_feed',array['text','integer','integer','text'],'feed ranking RPC');
select has_function('public','record_feed_interaction',array['uuid','text','text','integer','bigint','jsonb'],'interaction RPC');
select has_function('public','record_feed_feedback',array['uuid','text','uuid','uuid','text','text','jsonb'],'feedback RPC');
select is((select prosecdef from pg_proc where oid='public.get_feed(text,integer,integer,text)'::regprocedure),true,'feed RPC security definer');
select is((select prosecdef from pg_proc where oid='public.record_feed_interaction(uuid,text,text,integer,bigint,jsonb)'::regprocedure),true,'interaction RPC security definer');
select is((select prosecdef from pg_proc where oid='public.record_feed_feedback(uuid,text,uuid,uuid,text,text,jsonb)'::regprocedure),true,'feedback RPC security definer');
select is((select count(*) from public.feed_impressions),0::bigint,'no seeded impressions');
select is((select count(*) from public.feed_interaction_events),0::bigint,'no seeded interactions');
select is((select count(*) from public.feed_feedback),0::bigint,'no seeded feedback');
select * from finish();
rollback;