begin;
select plan(33);
select has_table('public','ai_providers','ai_providers exists');
select has_table('public','ai_models','ai_models exists');
select has_table('public','ai_model_capabilities','ai_model_capabilities exists');
select has_table('public','ai_routing_policies','ai_routing_policies exists');
select has_table('public','ai_gateway_requests','ai_gateway_requests exists');
select has_table('public','ai_gateway_attempts','ai_gateway_attempts exists');
select has_table('public','ai_usage_events','ai_usage_events exists');
select col_is_pk('public','ai_providers','id','provider id primary key');
select col_is_pk('public','ai_models','id','model id primary key');
select col_is_pk('public','ai_gateway_requests','id','request id primary key');
select col_is_pk('public','ai_gateway_attempts','id','attempt id primary key');
select col_is_pk('public','ai_usage_events','id','usage event id primary key');
select rls_enabled('public.ai_providers','providers RLS enabled');
select rls_enabled('public.ai_models','models RLS enabled');
select rls_enabled('public.ai_routing_policies','routing policies RLS enabled');
select rls_enabled('public.ai_gateway_requests','gateway requests RLS enabled');
select rls_enabled('public.ai_gateway_attempts','gateway attempts RLS enabled');
select rls_enabled('public.ai_usage_events','usage events RLS enabled');
select has_function('public','create_ai_gateway_request',array['uuid','text','text[]','text','jsonb'],'request RPC exists');
select has_function('public','record_ai_gateway_attempt',array['uuid','integer','uuid','uuid','text','integer','integer','integer','integer','numeric','integer','text','text'],'attempt RPC exists');
select has_function('public','record_ai_usage_event',array['uuid','text','uuid','uuid','uuid','integer','integer','integer','numeric','integer','jsonb'],'usage RPC exists');
select has_function('public','record_ai_gateway_outcome',array['uuid','text','text','uuid','uuid','integer','integer','integer','numeric','integer','text','text','text','jsonb'],'outcome RPC exists');
select results_eq($$select count(*)::bigint from public.ai_providers$$,$$values (0::bigint)$$,'no provider seed data');
select results_eq($$select count(*)::bigint from public.ai_models$$,$$values (0::bigint)$$,'no model seed data');
select results_eq($$select count(*)::bigint from public.ai_gateway_requests$$,$$values (0::bigint)$$,'no request seed data');
select results_eq($$select count(*)::bigint from public.ai_usage_events$$,$$values (0::bigint)$$,'no usage seed data');
select has_check('public','ai_providers','adapter','provider adapter constrained');
select has_check('public','ai_models','context_window_tokens','model context constrained');
select has_check('public','ai_routing_policies','scope_type','routing scope constrained');
select has_check('public','ai_gateway_requests','status','request status constrained');
select has_check('public','ai_gateway_requests','safety_status','safety status constrained');
select has_check('public','ai_gateway_attempts','status','attempt status constrained');
select has_check('public','ai_usage_events','event_type','usage event constrained');
select * from finish();
rollback;
