begin;
select plan(17);
select ok(to_regclass('public.agent_service_requests') is not null,'service requests exists');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='agent_service_requests' and column_name='skill_id'),'service request skill snapshot column exists');
select ok(to_regprocedure('public.reserve_agent_service_request(uuid,text,text,integer,text,uuid,uuid,jsonb)') is not null,'canonical reservation RPC exists');
select ok(to_regprocedure('public.list_verifiable_agent_service_requests(integer)') is not null,'verifiable service listing RPC exists');
select ok(to_regprocedure('public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)') is not null,'quality outcome RPC exists');
select ok(not has_function_privilege('anon','public.list_verifiable_agent_service_requests(integer)','execute'),'verifiable listing denied to anon');
select ok(has_function_privilege('authenticated','public.list_verifiable_agent_service_requests(integer)','execute'),'verifiable listing granted to authenticated');
select ok(not has_function_privilege('anon','public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)','execute'),'quality outcome denied to anon');
select ok(has_function_privilege('authenticated','public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)','execute'),'quality outcome granted to authenticated');
select ok((select prokind='f' and prosecdef from pg_proc where oid='public.list_verifiable_agent_service_requests(integer)'::regprocedure),'verifiable listing security definer');
select ok((select prosecdef from pg_proc where oid='public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)'::regprocedure),'quality outcome security definer');
select ok((select proconfig @> array['search_path=""'] from pg_proc where oid='public.list_verifiable_agent_service_requests(integer)'::regprocedure),'verifiable listing empty search_path');
select ok((select proconfig @> array['search_path='] from pg_proc where oid='public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)'::regprocedure),'quality outcome empty search_path');
select ok(pg_get_functiondef('public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)'::regprocedure) like '%SKILL_REWARD_SELF_USAGE_FORBIDDEN%','self reward guard');
select ok(pg_get_functiondef('public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)'::regprocedure) like '%SKILL_REWARD_REQUESTER_ONLY%','requester-only guard');
select ok(pg_get_functiondef('public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)'::regprocedure) like '%verified_cross_owner_usage_v1%','reward provenance');
select ok((select count(*) from public.agent_service_requests)=0,'no fake service requests');
select * from finish();
rollback;