-- Phase 22G invariants: Live Experience 3D Stage + Human Presentation Runtime.
select 1 as assertion where to_regclass('public.live_session_stage_bindings') is not null;
select 1 as assertion where to_regclass('public.live_session_camera_sources') is not null;
select 1 as assertion where to_regclass('public.live_human_presence_verifications') is not null;
select 1 as assertion where to_regclass('public.live_human_costume_templates') is not null;
select 1 as assertion where to_regclass('public.live_session_human_presentations') is not null;
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='bind_live_stage');
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='register_live_camera_source');
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='submit_live_human_presence_check');
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='bind_live_human_presentation');
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='activate_live_experience');
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='prepare_live_custom_costume');
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='finalize_live_custom_costume');
select 1 as assertion where exists(select 1 from pg_indexes where schemaname='public' and indexname='live_session_camera_active_unique');
select 1 as assertion where exists(select 1 from pg_indexes where schemaname='public' and indexname='live_human_presence_one_current_idx');
select 1 as assertion where exists(select 1 from pg_policies where schemaname='public' and tablename='live_session_stage_bindings' and policyname='live_stage_binding_read');
select 1 as assertion where exists(select 1 from pg_policies where schemaname='public' and tablename='live_session_camera_sources' and policyname='live_camera_source_owner_read');
select 1 as assertion where exists(select 1 from pg_policies where schemaname='public' and tablename='live_human_presence_verifications' and policyname='live_presence_owner_read');
select 1 as assertion where exists(select 1 from pg_policies where schemaname='public' and tablename='live_human_costume_templates' and policyname='live_custom_costume_owner_read');
select 1 as assertion where exists(select 1 from pg_policies where schemaname='public' and tablename='live_session_human_presentations' and policyname='live_human_presentation_owner_read');
select 1 as assertion where has_function_privilege('anon','public.bind_live_stage(uuid,uuid,uuid,jsonb)','execute')=false;
select 1 as assertion where has_function_privilege('authenticated','public.bind_live_stage(uuid,uuid,uuid,jsonb)','execute');
select 1 as assertion where has_function_privilege('anon','public.activate_live_experience(uuid,uuid)','execute')=false;
select 1 as assertion where has_function_privilege('authenticated','public.activate_live_experience(uuid,uuid)','execute');
select 1 as assertion where has_function_privilege('anon','public.prepare_live_custom_costume(text,text,text,jsonb)','execute')=false;
select 1 as assertion where has_function_privilege('authenticated','public.prepare_live_custom_costume(text,text,text,jsonb)','execute');
select 1 as assertion where not exists(select 1 from public.live_session_stage_bindings);
select 1 as assertion where not exists(select 1 from public.live_session_camera_sources);
select 1 as assertion where not exists(select 1 from public.live_human_presence_verifications);
select 1 as assertion where not exists(select 1 from public.live_human_costume_templates);
select 1 as assertion where not exists(select 1 from public.live_session_human_presentations);
select 1 as assertion where exists(select 1 from public.theme_assets where live_stage_component='LiveExperienceStage' and status='active' and moderation_status='approved' and safety_status='passed' and performance_status='passed');
select 1 as assertion where exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='moderate_live_custom_costume');
select 1 as assertion where has_function_privilege('anon','public.moderate_live_custom_costume(uuid,text)','execute')=false;
select 1 as assertion where has_function_privilege('authenticated','public.moderate_live_custom_costume(uuid,text)','execute');
