begin;
select plan(31);
select has_table('public','districts','districts table');
select has_table('public','district_memberships','district memberships table');
select has_table('public','district_entitlements','district entitlements table');
select has_table('public','district_zones','district zones table');
select has_table('public','district_access_requests','district access requests table');
select has_table('public','district_activity_events','district activity events table');
select ok((select relrowsecurity from pg_class where oid='public.districts'::regclass),'districts RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_memberships'::regclass),'memberships RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_entitlements'::regclass),'entitlements RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_zones'::regclass),'zones RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_access_requests'::regclass),'requests RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_activity_events'::regclass),'events RLS enabled');
select has_function('public','create_district',ARRAY['uuid','text','uuid','text','text','text','text','text','text','jsonb','jsonb'],'create_district RPC');
select has_function('public','publish_district',ARRAY['uuid'],'publish_district RPC');
select has_function('public','join_district',ARRAY['uuid','text','uuid'],'join_district RPC');
select has_function('public','request_district_access',ARRAY['uuid','text','uuid','text','text','jsonb'],'request access RPC');
select has_function('public','decide_district_access',ARRAY['uuid','text','text','text'],'decide access RPC');
select has_function('public','grant_district_entitlement',ARRAY['uuid','text','uuid','text','text','timestamptz','timestamptz','jsonb'],'grant entitlement RPC');
select has_function('public','revoke_district_entitlement',ARRAY['uuid'],'revoke entitlement RPC');
select has_function('public','create_district_zone',ARRAY['uuid','text','text','text','jsonb','jsonb'],'create zone RPC');
select has_function('public','activate_district_zone',ARRAY['uuid'],'activate zone RPC');
select ok((select prosecdef from pg_proc where oid='public.create_district(uuid,text,uuid,text,text,text,text,text,text,jsonb,jsonb)'::regprocedure),'create district is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.publish_district(uuid)'::regprocedure),'publish district is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.join_district(uuid,text,uuid)'::regprocedure),'join district is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.grant_district_entitlement(uuid,text,uuid,text,text,timestamptz,timestamptz,jsonb)'::regprocedure),'grant entitlement is SECURITY DEFINER');
select ok((select proconfig @> ARRAY['search_path='] from pg_proc where oid='public.create_district(uuid,text,uuid,text,text,text,text,text,text,jsonb,jsonb)'::regprocedure),'create district pins empty search_path');
select ok((select proconfig @> ARRAY['search_path='] from pg_proc where oid='public.grant_district_entitlement(uuid,text,uuid,text,text,timestamptz,timestamptz,jsonb)'::regprocedure),'entitlement RPC pins empty search_path');
select is((select count(*)::int from public.districts),0,'no district seed data');
select is((select count(*)::int from public.district_memberships),0,'no membership seed data');
select is((select count(*)::int from public.district_entitlements),0,'no entitlement seed data');
select is((select count(*)::int from public.district_access_requests),0,'no access request seed data');
select * from finish();
rollback;