begin;
select plan(32);
select ok(to_regclass('public.themes') is not null,'themes table exists');
select ok(to_regclass('public.theme_versions') is not null,'theme_versions table exists');
select ok(to_regclass('public.theme_assets') is not null,'theme_assets table exists');
select ok(to_regclass('public.world_templates') is not null,'world_templates table exists');
select ok(to_regclass('public.world_template_versions') is not null,'world_template_versions table exists');
select ok(to_regclass('public.world_builder_states') is not null,'world_builder_states table exists');
select ok((select relrowsecurity from pg_class where oid='public.themes'::regclass),'themes RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.theme_versions'::regclass),'theme versions RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.theme_assets'::regclass),'theme assets RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.world_templates'::regclass),'world templates RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.world_template_versions'::regclass),'world template versions RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.world_builder_states'::regclass),'builder state RLS enabled');
select ok(to_regprocedure('public.create_theme(text,text,text,text,jsonb,jsonb,jsonb,jsonb)') is not null,'create theme RPC exists');
select ok(to_regprocedure('public.create_theme_version(uuid,jsonb,jsonb,jsonb,jsonb,jsonb,jsonb)') is not null,'create theme version RPC exists');
select ok(to_regprocedure('public.add_theme_asset(uuid,text,text,text,jsonb,integer)') is not null,'theme asset RPC exists');
select ok(to_regprocedure('public.validate_theme_version(uuid)') is not null,'theme validation RPC exists');
select ok(to_regprocedure('public.submit_theme(uuid)') is not null,'theme submit RPC exists');
select ok(to_regprocedure('public.publish_theme(uuid)') is not null,'theme publish RPC exists');
select ok(to_regprocedure('public.create_world_template(text,text,text,text,jsonb)') is not null,'world template RPC exists');
select ok(to_regprocedure('public.create_world_template_version(uuid,uuid,uuid,jsonb,jsonb)') is not null,'world template version RPC exists');
select ok(to_regprocedure('public.save_world_builder_state(uuid,uuid,uuid,uuid,uuid,uuid,jsonb)') is not null,'builder save RPC exists');
select ok(to_regprocedure('public.validate_world_builder_state(uuid)') is not null,'builder validation RPC exists');
select ok(to_regprocedure('public.submit_world_builder_state(uuid)') is not null,'builder submit RPC exists');
select ok((select prosecdef from pg_proc where oid='public.create_theme(text,text,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure),'theme create SECURITY DEFINER');
select ok((select proconfig @> ARRAY['search_path=""'] from pg_proc where oid='public.create_theme(text,text,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure),'theme create empty search_path');
select ok((select prosecdef from pg_proc where oid='public.publish_theme(uuid)'::regprocedure),'theme publish SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.save_world_builder_state(uuid,uuid,uuid,uuid,uuid,uuid,jsonb)'::regprocedure),'builder save SECURITY DEFINER');
select ok((select proconfig @> ARRAY['search_path=""'] from pg_proc where oid='public.save_world_builder_state(uuid,uuid,uuid,uuid,uuid,uuid,jsonb)'::regprocedure),'builder save empty search_path');
select is((select count(*)::int from public.themes),0,'no theme seed data');
select is((select count(*)::int from public.theme_versions),0,'no theme version seed data');
select is((select count(*)::int from public.theme_assets),0,'no theme asset seed data');
select is((select count(*)::int from public.world_templates),0,'no world template seed data');
select is((select count(*)::int from public.world_template_versions),0,'no world template version seed data');
select is((select count(*)::int from public.world_builder_states),0,'no builder seed data');
select * from finish();
rollback;