-- Phase 17 AI Universe invariants
select plan(32);
select ok(to_regclass('public.universe_galaxies') is not null,'universe_galaxies exists');
select ok(to_regclass('public.universe_worlds') is not null,'universe_worlds exists');
select ok(to_regclass('public.universe_world_memberships') is not null,'world memberships exists');
select ok(to_regclass('public.universe_world_interests') is not null,'world interests exists');
select ok(to_regclass('public.universe_world_content') is not null,'world content exists');
select ok(to_regclass('public.universe_world_communities') is not null,'world communities exists');
select ok(to_regclass('public.universe_world_agents') is not null,'world agents exists');
select ok(to_regclass('public.universe_world_portals') is not null,'world portals exists');
select ok(to_regclass('public.universe_agent_presences') is not null,'agent presences exists');
select ok((select relrowsecurity from pg_class where oid='public.universe_galaxies'::regclass),'galaxies RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_worlds'::regclass),'worlds RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_world_memberships'::regclass),'memberships RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_world_interests'::regclass),'interests RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_world_content'::regclass),'content links RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_world_communities'::regclass),'community links RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_world_agents'::regclass),'agent links RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_world_portals'::regclass),'portals RLS');
select ok((select relrowsecurity from pg_class where oid='public.universe_agent_presences'::regclass),'presence RLS');
select ok(to_regprocedure('public.create_universe_galaxy(text,uuid,text,text,text,text,jsonb)') is not null,'create galaxy RPC');
select ok(to_regprocedure('public.create_universe_world(uuid,text,uuid,text,text,text,text,text,text,jsonb,jsonb)') is not null,'create world RPC');
select ok(to_regprocedure('public.publish_universe_world(uuid)') is not null,'publish world RPC');
select ok(to_regprocedure('public.join_universe_world(uuid,text,uuid)') is not null,'join world RPC');
select ok(to_regprocedure('public.link_universe_world_interest(uuid,uuid,numeric)') is not null,'interest link RPC');
select ok(to_regprocedure('public.link_universe_world_content(uuid,uuid,text,integer)') is not null,'content link RPC');
select ok(to_regprocedure('public.link_universe_world_community(uuid,uuid,text)') is not null,'community link RPC');
select ok(to_regprocedure('public.link_universe_world_agent(uuid,uuid,text)') is not null,'agent link RPC');
select ok(to_regprocedure('public.create_universe_portal(uuid,uuid,text,text,jsonb)') is not null,'portal RPC');
select ok(to_regprocedure('public.upsert_universe_agent_presence(uuid,uuid,text,text,jsonb)') is not null,'presence RPC');
select ok(to_regprocedure('public.exit_universe_agent_presence(uuid,uuid)') is not null,'exit presence RPC');
select ok((select count(*) from public.universe_galaxies)=0,'no galaxy seed data');
select ok((select count(*) from public.universe_worlds)=0,'no world seed data');
select ok((select count(*) from public.universe_agent_presences)=0,'no presence seed data');
select * from finish();