begin;
select plan(32);
select has_table('public','content_items','content items exists');
select has_table('public','content_media_assets','media asset table exists');
select has_table('public','content_media','content media links exist');
select has_table('public','content_topics','content topics exists');
select has_table('public','content_topic_links','content topic links exist');
select has_table('public','content_revisions','content revisions exist');
select has_table('public','content_moderation_cases','moderation cases exist');
select has_table('public','ai_capsules','AI capsules exist');
select has_table('public','content_events','content events exist');
select is((select relrowsecurity from pg_class where oid='public.content_items'::regclass),true,'content items RLS');
select is((select relrowsecurity from pg_class where oid='public.content_media_assets'::regclass),true,'media assets RLS');
select is((select relrowsecurity from pg_class where oid='public.content_media'::regclass),true,'content media RLS');
select is((select relrowsecurity from pg_class where oid='public.content_topics'::regclass),true,'topics RLS');
select is((select relrowsecurity from pg_class where oid='public.content_topic_links'::regclass),true,'topic links RLS');
select is((select relrowsecurity from pg_class where oid='public.content_revisions'::regclass),true,'revisions RLS');
select is((select relrowsecurity from pg_class where oid='public.content_moderation_cases'::regclass),true,'moderation RLS');
select is((select relrowsecurity from pg_class where oid='public.ai_capsules'::regclass),true,'capsules RLS');
select is((select relrowsecurity from pg_class where oid='public.content_events'::regclass),true,'events RLS');
select has_function('public','create_content',array['text','uuid','text','text','text','text','text','text','jsonb'],'create content RPC');
select has_function('public','update_content',array['uuid','text','text','text','text','text','jsonb'],'update content RPC');
select has_function('public','publish_content',array['uuid'],'publish content RPC');
select has_function('public','archive_content',array['uuid'],'archive content RPC');
select has_function('public','create_media_asset',array['text','uuid','text','text','text','text','text','bigint','text','integer','integer','bigint','jsonb'],'media RPC');
select has_function('public','attach_content_media',array['uuid','uuid','text','integer','text','text','jsonb'],'attach media RPC');
select has_function('public','submit_content_moderation',array['uuid','text','text'],'moderation RPC');
select has_function('public','record_content_event',array['uuid','text','jsonb'],'content event RPC');
select has_function('public','create_ai_capsule',array['uuid','text','jsonb','jsonb','text','text','jsonb','numeric'],'AI capsule RPC');
select is((select count(*) from public.content_items),0::bigint,'no seeded content');
select is((select count(*) from public.content_media_assets),0::bigint,'no seeded media');
select is((select count(*) from public.content_topics),0::bigint,'no seeded topics');
select is((select count(*) from public.content_moderation_cases),0::bigint,'no seeded moderation cases');
select is((select count(*) from public.ai_capsules),0::bigint,'no seeded capsules');
select * from finish();
rollback;