begin;
select plan(48);
select has_table('public','agent_commands','agent_commands exists');
select has_table('public','agent_execution_contexts','execution contexts exists');
select has_table('public','agent_tasks','agent tasks exists');
select has_table('public','agent_task_steps','agent task steps exists');
select has_table('public','agent_tool_definitions','tool definitions exists');
select has_table('public','agent_tool_runs','tool runs exists');
select has_table('public','agent_kill_switches','kill switches exists');
select has_table('public','agent_runtime_events','runtime events exists');
select has_table('public','agent_spend_events','spend events exists');
select rls_enabled('public.agent_commands','commands RLS');
select rls_enabled('public.agent_execution_contexts','contexts RLS');
select rls_enabled('public.agent_tasks','tasks RLS');
select rls_enabled('public.agent_task_steps','steps RLS');
select rls_enabled('public.agent_tool_definitions','tools RLS');
select rls_enabled('public.agent_tool_runs','tool runs RLS');
select rls_enabled('public.agent_kill_switches','kill switch RLS');
select rls_enabled('public.agent_runtime_events','runtime events RLS');
select rls_enabled('public.agent_spend_events','spend RLS');
select has_function('public','create_agent_command',array['uuid','text','text[]','text'],'command create RPC');
select has_function('public','materialize_agent_plan',array['uuid','jsonb'],'plan materialize RPC');
select has_function('public','begin_agent_execution',array['uuid'],'execution start RPC');
select has_function('public','resume_agent_after_approval',array['uuid'],'approval resume RPC');
select has_function('public','record_agent_tool_result',array['uuid','text','jsonb','text','text','integer','text'],'tool result RPC');
select has_function('public','record_agent_spend',array['uuid','uuid','uuid','numeric','text','jsonb'],'spend RPC');
select has_function('public','transition_agent_command',array['uuid','text','text','text','text'],'transition RPC');
select has_function('public','set_agent_kill_switch',array['uuid','boolean','text'],'kill switch RPC');
select has_function('public','decide_agent_approval',array['uuid','text','text'],'approval decision RPC');
select results_eq($$select count(*)::bigint from public.agent_commands$$,$$values (0::bigint)$$,'no command seed data');
select results_eq($$select count(*)::bigint from public.agent_execution_contexts$$,$$values (0::bigint)$$,'no context seed data');
select results_eq($$select count(*)::bigint from public.agent_tasks$$,$$values (0::bigint)$$,'no task seed data');
select results_eq($$select count(*)::bigint from public.agent_task_steps$$,$$values (0::bigint)$$,'no step seed data');
select results_eq($$select count(*)::bigint from public.agent_tool_runs$$,$$values (0::bigint)$$,'no tool run seed data');
select results_eq($$select count(*)::bigint from public.agent_runtime_events$$,$$values (0::bigint)$$,'no runtime event seed data');
select results_eq($$select count(*)::bigint from public.agent_spend_events$$,$$values (0::bigint)$$,'no spend seed data');
select results_eq($$select count(*)::bigint from public.agent_tool_definitions where tool_key='ai.generate'$$,$$values (1::bigint)$$,'canonical AI Gateway tool registered');
select ok(exists(select 1 from pg_constraint where conrelid='public.agent_commands'::regclass and conname='agent_commands_status_check'),'command status constrained');
select ok(exists(select 1 from pg_constraint where conrelid='public.agent_commands'::regclass and conname='agent_commands_risk_decision_check'),'command risk decision constrained');
select ok(exists(select 1 from pg_constraint where conrelid='public.agent_task_steps'::regclass and conname='agent_task_steps_status_check'),'step status constrained');
select ok(exists(select 1 from pg_constraint where conrelid='public.agent_spend_events'::regclass and conname='agent_spend_events_amount_check'),'spend amount constrained');
select ok((select prosecdef from pg_proc where oid='public.create_agent_command(uuid,text,text[],text)'::regprocedure),'create command is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.materialize_agent_plan(uuid,jsonb)'::regprocedure),'plan materializer is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.begin_agent_execution(uuid)'::regprocedure),'execution start is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.decide_agent_approval(uuid,text,text)'::regprocedure),'approval decision is SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.set_agent_kill_switch(uuid,boolean,text)'::regprocedure),'kill switch is SECURITY DEFINER');
select ok((select proconfig @> array['search_path='] from pg_proc where oid='public.create_agent_command(uuid,text,text[],text)'::regprocedure),'create command search_path pinned');
select ok((select proconfig @> array['search_path='] from pg_proc where oid='public.begin_agent_execution(uuid)'::regprocedure),'execution search_path pinned');
select ok((select proconfig @> array['search_path='] from pg_proc where oid='public.set_agent_kill_switch(uuid,boolean,text)'::regprocedure),'kill switch search_path pinned');
select ok((select proconfig @> array['search_path='] from pg_proc where oid='public.record_agent_spend(uuid,uuid,uuid,numeric,text,jsonb)'::regprocedure),'spend search_path pinned');

select * from finish();
rollback;
