begin;
select plan(18);
select ok((select count(*) from public.themes where source='platform')=25,'25 platform themes');
select ok((select count(*) from public.theme_versions tv join public.themes t on t.id=tv.theme_id where t.source='platform' and tv.status='published')=25,'25 published platform theme versions');
select ok((select count(*) from public.world_templates where source='platform')=25,'25 platform world templates');
select ok((select count(*) from public.world_template_versions wv join public.world_templates w on w.id=wv.world_template_id where w.source='platform' and wv.status='published')=25,'25 published world template versions');
select ok((select count(*) from public.theme_assets where status='active')=25,'25 active theme 3D assets');
select ok((select count(*) from public.agent_skill_catalog)>0,'skill catalog available');
select ok(to_regclass('public.agent_skills') is not null,'agent skills table exists');
select ok(to_regclass('public.agent_skill_challenge_events') is not null,'skill challenge events exists');
select ok(to_regclass('public.agent_skill_challenge_leaderboard') is not null,'skill leaderboard exists');
select ok((select relrowsecurity from pg_class where oid='public.agent_skill_challenge_events'::regclass),'challenge events RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.agent_skill_challenge_leaderboard'::regclass),'leaderboard RLS enabled');
select ok(to_regprocedure('public.upsert_agent_skill(uuid,uuid,text,text,text,text,jsonb,boolean)') is not null,'skill upsert RPC exists');
select ok(to_regprocedure('public.publish_agent_skill(uuid)') is not null,'skill publish RPC exists');
select ok(to_regprocedure('public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)') is not null,'skill reward RPC exists');
select ok(not has_function_privilege('anon','public.upsert_agent_skill(uuid,uuid,text,text,text,text,jsonb,boolean)','execute'),'skill upsert denied to anon');
select ok(not has_function_privilege('anon','public.record_agent_skill_quality_outcome(uuid,numeric,jsonb,jsonb)','execute'),'skill reward denied to anon');
select ok((select count(*) from public.agent_skills)=0,'no fake user skills');
select ok((select count(*) from public.agent_skill_challenge_events)=0,'no fake challenge events');
select * from finish(); rollback;