begin;
select plan(26);
select ok(to_regclass('public.districts') is not null,'districts table exists');
select ok(to_regclass('public.district_memberships') is not null,'district memberships table exists');
select ok(to_regclass('public.district_entitlements') is not null,'district entitlements table exists');
select ok(to_regclass('public.district_zones') is not null,'district zones table exists');
select ok(to_regclass('public.district_access_requests') is not null,'district access requests table exists');
select ok(to_regclass('public.district_activity_events') is not null,'district activity events table exists');
select ok((select relrowsecurity from pg_class where oid='public.districts'::regclass),'districts RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_memberships'::regclass),'memberships RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_entitlements'::regclass),'entitlements RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_zones'::regclass),'zones RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_access_requests'::regclass),'requests RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.district_activity_events'::regclass),'events RLS enabled');
select ok(to_regprocedure('public.create_district(uuid,text,uuid,text,text,text,text,text,text,jsonb,jsonb)') is not null,'create district RPC exists');
select ok(to_regprocedure('public.publish_district(uuid)') is not null,'publish district RPC exists');
select ok(to_regprocedure('public.join_district(uuid,text,uuid)') is not null,'join district RPC exists');
select ok(to_regprocedure('public.request_district_access(uuid,text,uuid,text,text,jsonb)') is not null,'request access RPC exists');
select ok(to_regprocedure('public.decide_district_access(uuid,text,text,text)') is not null,'decide access RPC exists');
select ok(to_regprocedure('public.grant_district_entitlement(uuid,text,uuid,text,text,timestamptz,timestamptz,jsonb)') is not null,'grant entitlement RPC exists');
select ok(to_regprocedure('public.revoke_district_entitlement(uuid)') is not null,'revoke entitlement RPC exists');
select ok(to_regprocedure('public.create_district_zone(uuid,text,text,text,jsonb,jsonb)') is not null,'create zone RPC exists');
select ok(to_regprocedure('public.activate_district_zone(uuid)') is not null,'activate zone RPC exists');
select ok((select prosecdef from pg_proc where oid='public.create_district(uuid,text,uuid,text,text,text,text,text,text,jsonb,jsonb)'::regprocedure),'create district SECURITY DEFINER');
select ok((select proconfig @> ARRAY['search_path=""'] from pg_proc where oid='public.create_district(uuid,text,uuid,text,text,text,text,text,text,jsonb,jsonb)'::regprocedure),'create district empty search_path');
select ok((select prosecdef from pg_proc where oid='public.grant_district_entitlement(uuid,text,uuid,text,text,timestamptz,timestamptz,jsonb)'::regprocedure),'grant entitlement SECURITY DEFINER');
select is((select count(*)::int from public.districts),0,'no district seed data');
select is((select count(*)::int from public.district_entitlements),0,'no entitlement seed data');
select * from finish();
rollback;