begin;
select plan(29);
select has_table('public','feed_impressions','feed impressions exists');
select has_table('public','feed_interaction_events','feed interaction events exists');
select has_table('public','feed_feedback','feed feedback exists');
select is((select relrowsecurity from pg_class where oid='public.feed_impressions'::regclass),true,'impressions RLS');
select is((select relrowsecurity from pg_class where oid='public.feed_interaction_events'::regclass),true,'interaction RLS');
select is((select relrowsecurity from pg_class where oid='public.feed_feedback'::regclass),true,'feedback RLS');
select has_function('public','get_feed',array['text','integer','integer','text'],'feed ranking RPC');
select has_function('public','record_feed_interaction',array['uuid','text','text','integer','bigint','jsonb'],'interaction RPC');
select has_function('public','record_feed_feedback',array['uuid','text','uuid','uuid','text','text','jsonb'],'feedback RPC');
select is((select prosecdef from pg_proc where oid='public.get_feed(text,integer,integer,text)'::regprocedure),true,'feed RPC security definer');
select is((select prosecdef from pg_proc where oid='public.record_feed_interaction(uuid,text,text,integer,bigint,jsonb)'::regprocedure),true,'interaction RPC security definer');
select is((select prosecdef from pg_proc where oid='public.record_feed_feedback(uuid,text,uuid,uuid,text,text,jsonb)'::regprocedure),true,'feedback RPC security definer');
select is((select count(*) from public.feed_impressions),0::bigint,'no seeded impressions');
select is((select count(*) from public.feed_interaction_events),0::bigint,'no seeded interactions');
select is((select count(*) from public.feed_feedback),0::bigint,'no seeded feedback');
select has_index('public','feed_impressions_user_created_idx','impression user index');
select has_index('public','feed_impressions_content_idx','impression content index');
select has_index('public','feed_interaction_events_user_created_idx','interaction user index');
select has_index('public','feed_interaction_events_content_created_idx','interaction content index');
select has_index('public','feed_feedback_user_created_idx','feedback user index');
select has_index('public','feed_feedback_content_idx','feedback content index');
select has_index('public','feed_feedback_owner_idx','feedback owner index');
select has_index('public','feed_feedback_topic_idx','feedback topic index');
select has_index('public','content_items_published_created_idx','published content index');
select has_index('public','content_items_type_published_idx','content type index');
select has_index('public','content_topic_links_topic_content_idx','topic link index');
select has_index('public','social_relationships_follow_source_target_idx','follow ranking index');
select * from finish();
rollback;