begin;
select plan(20);
select ok(to_regclass('public.live_session_character_bindings') is not null,'Live character binding table exists');
select ok(to_regprocedure('public.select_live_character(uuid,uuid,uuid,jsonb)') is not null,'Live character selection RPC exists');
select ok(to_regprocedure('public.remove_live_character(uuid)') is not null,'Live character removal RPC exists');
select ok(lower(pg_get_functiondef('public.select_live_character(uuid,uuid,uuid,jsonb)'::regprocedure)) like '%security definer%','character selection is SECURITY DEFINER');
select ok(pg_get_functiondef('public.select_live_character(uuid,uuid,uuid,jsonb)'::regprocedure) like '%search_path TO ''''%','character selection pins empty search_path');
select ok(lower(pg_get_functiondef('public.remove_live_character(uuid)'::regprocedure)) like '%security definer%','character removal is SECURITY DEFINER');
select ok(has_function_privilege('anon','public.select_live_character(uuid,uuid,uuid,jsonb)','execute') is false,'anon cannot select character');
select ok(has_function_privilege('authenticated','public.select_live_character(uuid,uuid,uuid,jsonb)','execute'),'authenticated can select character');
select ok(has_function_privilege('anon','public.remove_live_character(uuid)','execute') is false,'anon cannot remove character');
select ok(has_function_privilege('authenticated','public.remove_live_character(uuid)','execute'),'authenticated can remove character');
select ok(pg_get_functiondef('public.create_live_session_message(uuid,text,text,uuid,uuid)'::regprocedure) like '%AGENT_KILL_SWITCH_ENABLED%','Live Agent message rechecks kill switch');
select ok(pg_get_functiondef('public.create_live_session_message(uuid,text,text,uuid,uuid)'::regprocedure) like '%AGENT_CAPABILITY_NOT_GRANTED%','Live Agent message rechecks capability');
select ok(pg_get_functiondef('public.create_live_session_message(uuid,text,text,uuid,uuid)'::regprocedure) like '%LIVE_COLLAB_POLICY_DENIED%','Live Agent message rechecks policy');
select ok(exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='live_session_character_bindings'),'character bindings published to Realtime');
select ok((select count(*) from public.live_session_character_bindings)=0,'no synthetic character bindings');
select ok((select count(*) from public.live_sessions)=0,'no synthetic Live sessions');
select ok(to_regprocedure('public.start_live_session(uuid,text,text)') is not null,'Live start lifecycle RPC exists');
select ok(to_regprocedure('public.end_live_session(uuid)') is not null,'Live end lifecycle RPC exists');
select ok(has_function_privilege('anon','public.start_live_session(uuid,text,text)','execute') is false,'anon cannot start Live');
select ok(has_function_privilege('authenticated','public.start_live_session(uuid,text,text)','execute'),'authenticated can start Live');
select * from finish();
rollback;