-- Phase 16 Workflow & Mission Engine invariants
select plan(35);
select ok(to_regclass('public.workflows') is not null,'workflows table exists');
select ok(to_regclass('public.workflow_versions') is not null,'workflow_versions table exists');
select ok(to_regclass('public.workflow_steps') is not null,'workflow_steps table exists');
select ok(to_regclass('public.workflow_runs') is not null,'workflow_runs table exists');
select ok(to_regclass('public.workflow_run_steps') is not null,'workflow_run_steps table exists');
select ok(to_regclass('public.workflow_events') is not null,'workflow_events table exists');
select ok(to_regclass('public.missions') is not null,'missions table exists');
select ok(to_regclass('public.mission_participants') is not null,'mission_participants table exists');
select ok(to_regclass('public.mission_runs') is not null,'mission_runs table exists');
select ok((select relrowsecurity from pg_class where oid='public.workflows'::regclass),'workflows RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.workflow_versions'::regclass),'workflow_versions RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.workflow_steps'::regclass),'workflow_steps RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.workflow_runs'::regclass),'workflow_runs RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.workflow_run_steps'::regclass),'workflow_run_steps RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.workflow_events'::regclass),'workflow_events RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.missions'::regclass),'missions RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.mission_participants'::regclass),'mission_participants RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.mission_runs'::regclass),'mission_runs RLS enabled');
select ok(to_regprocedure('public.create_workflow(text,uuid,text,text,text,text,jsonb)') is not null,'create_workflow exists');
select ok(to_regprocedure('public.create_workflow_version(uuid,jsonb,jsonb)') is not null,'create_workflow_version exists');
select ok(to_regprocedure('public.add_workflow_step(uuid,text,text,text,integer,text,jsonb,jsonb,jsonb,jsonb,risk_level,boolean)') is not null,'add_workflow_step exists');
select ok(to_regprocedure('public.publish_workflow_version(uuid)') is not null,'publish_workflow_version exists');
select ok(to_regprocedure('public.create_workflow_run(uuid,uuid,jsonb)') is not null,'create_workflow_run exists');
select ok(to_regprocedure('public.prepare_workflow_run(uuid)') is not null,'prepare_workflow_run exists');
select ok(to_regprocedure('public.sync_workflow_run(uuid)') is not null,'sync_workflow_run exists');
select ok(to_regprocedure('public.create_mission(text,uuid,uuid,text,text,text,text,integer,jsonb)') is not null,'create_mission exists');
select ok(to_regprocedure('public.join_mission(uuid,text,uuid)') is not null,'join_mission exists');
select ok(to_regprocedure('public.start_mission_run(uuid,uuid,uuid,jsonb)') is not null,'start_mission_run exists');
select ok(to_regprocedure('public.sync_mission_run(uuid)') is not null,'sync_mission_run exists');
select ok(to_regprocedure('public.publish_mission(uuid)') is not null,'publish_mission exists');
select ok(to_regprocedure('public.decide_mission_participant(uuid,text)') is not null,'decide_mission_participant exists');
select ok(to_regprocedure('public.create_shared_workflow_run(uuid,uuid,uuid,uuid,jsonb)') is not null,'create_shared_workflow_run exists');
select ok((select count(*) from public.workflows)=0,'no workflow seed data');
select ok((select count(*) from public.workflow_runs)=0,'no workflow run seed data');
select ok((select count(*) from public.missions)=0,'no mission seed data');
select ok(to_regprocedure('public.cancel_workflow_run(uuid,text)') is not null,'cancel_workflow_run exists');
select ok(to_regprocedure('public.cancel_mission_run(uuid,text)') is not null,'cancel_mission_run exists');
select ok(exists(select 1 from pg_proc p where p.oid='public.cancel_workflow_run(uuid,text)'::regprocedure and has_function_privilege('anon',p.oid,'execute')=false and has_function_privilege('authenticated',p.oid,'execute')),'cancel workflow authenticated-only');
select ok(exists(select 1 from pg_proc p where p.oid='public.cancel_mission_run(uuid,text)'::regprocedure and has_function_privilege('anon',p.oid,'execute')=false and has_function_privilege('authenticated',p.oid,'execute')),'cancel mission authenticated-only');
select ok(exists(select 1 from pg_proc p where p.oid='public.prepare_workflow_run(uuid)'::regprocedure and pg_get_functiondef(p.oid) like '%create_agent_command%'),'workflow delegates command creation to Agent Runtime');
select ok(exists(select 1 from pg_proc p where p.oid='public.cancel_workflow_run(uuid,text)'::regprocedure and pg_get_functiondef(p.oid) like '%cancel_agent_command%'),'workflow cancellation delegates to Agent Runtime');
select * from finish();
