begin;
select plan(25);
select ok(to_regclass('public.booths') is not null,'booths table exists');
select ok(to_regclass('public.booth_leases') is not null,'booth leases table exists');
select ok(to_regclass('public.booth_display_assets') is not null,'booth assets table exists');
select ok(to_regclass('public.booth_display_slots') is not null,'booth slots table exists');
select ok(to_regclass('public.booth_activity_events') is not null,'booth activity events table exists');
select ok((select relrowsecurity from pg_class where oid='public.booths'::regclass),'booths RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.booth_leases'::regclass),'leases RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.booth_display_assets'::regclass),'assets RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.booth_display_slots'::regclass),'slots RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.booth_activity_events'::regclass),'activity RLS enabled');
select ok(to_regprocedure('public.create_booth(uuid,uuid,text,uuid,uuid,text,text,text,text,text,text,jsonb,jsonb,jsonb,jsonb)') is not null,'create booth RPC exists');
select ok(to_regprocedure('public.update_booth(uuid,text,text,text,jsonb,jsonb,jsonb,jsonb)') is not null,'update booth RPC exists');
select ok(to_regprocedure('public.add_booth_asset(uuid,text,text,text,jsonb,integer)') is not null,'asset RPC exists');
select ok(to_regprocedure('public.bind_booth_slot(uuid,text,uuid,jsonb)') is not null,'slot RPC exists');
select ok(to_regprocedure('public.submit_booth(uuid)') is not null,'submit booth RPC exists');
select ok(to_regprocedure('public.publish_booth(uuid)') is not null,'publish booth RPC exists');
select ok(to_regprocedure('public.request_booth_lease(uuid,text,text,text,numeric,text,text,timestamptz,timestamptz,jsonb)') is not null,'lease request RPC exists');
select ok(to_regprocedure('public.activate_booth_lease(uuid)') is not null,'lease activation RPC exists');
select ok((select prosecdef from pg_proc where oid='public.create_booth(uuid,uuid,text,uuid,uuid,text,text,text,text,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure),'create booth SECURITY DEFINER');
select ok((select proconfig @> ARRAY['search_path=""'] from pg_proc where oid='public.create_booth(uuid,uuid,text,uuid,uuid,text,text,text,text,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure),'create booth empty search_path');
select ok((select prosecdef from pg_proc where oid='public.add_booth_asset(uuid,text,text,text,jsonb,integer)'::regprocedure),'asset SECURITY DEFINER');
select ok((select prosecdef from pg_proc where oid='public.publish_booth(uuid)'::regprocedure),'publish SECURITY DEFINER');
select is((select count(*)::int from public.booths),0,'no booth seed data');
select is((select count(*)::int from public.booth_leases),0,'no lease seed data');
select is((select count(*)::int from public.booth_display_assets),0,'no asset seed data');
select * from finish();
rollback;