"use client";

import { FormEvent, useEffect, useState } from "react";
import { apiFetch } from "../lib/api";

type Authority={agent:any;identity:any;passport:any;policy:any;budget:any;capabilities:any[];permissions:any[];risk_assessments:any[];approval_requests:any[];audit_logs:any[];runtime_events:any[]};

const input="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-slate-200 outline-none focus:border-cyan-300/40";
const btn="rounded-xl border border-white/10 px-4 py-2 text-xs hover:border-cyan-300/30 disabled:opacity-40";

export default function AgentControlSurface({agentId}:{agentId:string}){
 const [authority,setAuthority]=useState<Authority|null>(null),[capability,setCapability]=useState(""),[resource,setResource]=useState(""),[action,setAction]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);

 async function load(){setError(null);try{const r=await apiFetch<{data:Authority}>(`/api/v1/agents/${agentId}/authority`);setAuthority(r.data)}catch(e){setError(e instanceof Error?e.message:"AGENT_AUTHORITY_LOAD_FAILED")}}
 useEffect(()=>{void load()},[agentId]);

 async function addCapability(e:FormEvent){e.preventDefault();if(!capability.trim())return;setBusy(true);try{await apiFetch(`/api/v1/agents/${agentId}/capabilities`,{method:"POST",body:JSON.stringify({capability:capability.trim(),constraints:{}})});setCapability("");await load()}catch(e){setError(e instanceof Error?e.message:"CAPABILITY_ADD_FAILED")}finally{setBusy(false)}}
 async function toggleCapability(id:string,enabled:boolean){setBusy(true);try{await apiFetch(`/api/v1/agents/${agentId}/capabilities/${id}`,{method:"PATCH",body:JSON.stringify({enabled})});await load()}catch(e){setError(e instanceof Error?e.message:"CAPABILITY_STATE_UPDATE_FAILED")}finally{setBusy(false)}}
 async function addPermission(e:FormEvent){e.preventDefault();if(!resource.trim()||!action.trim())return;setBusy(true);try{await apiFetch(`/api/v1/agents/${agentId}/permissions`,{method:"POST",body:JSON.stringify({resource:resource.trim(),action:action.trim(),effect:"allow",scope:{}})});setResource("");setAction("");await load()}catch(e){setError(e instanceof Error?e.message:"PERMISSION_ADD_FAILED")}finally{setBusy(false)}}
 async function revokePermission(id:string){setBusy(true);try{await apiFetch(`/api/v1/agents/${agentId}/permissions/${id}`,{method:"DELETE"});await load()}catch(e){setError(e instanceof Error?e.message:"PERMISSION_REVOKE_FAILED")}finally{setBusy(false)}}
 async function verify(){setBusy(true);try{await apiFetch(`/api/v1/agents/${agentId}/verification/request`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"VERIFICATION_REQUEST_FAILED")}finally{setBusy(false)}}
 async function decide(commandId:string,decision:"approved"|"rejected"){setBusy(true);try{await apiFetch(`/api/v1/agent-runtime/commands/${commandId}/approval`,{method:"POST",body:JSON.stringify({decision})});await load()}catch(e){setError(e instanceof Error?e.message:"AGENT_APPROVAL_DECISION_FAILED")}finally{setBusy(false)}}

 return <main className="min-h-screen bg-slate-950 px-4 py-7 text-white sm:px-8"><div className="mx-auto max-w-7xl">
  <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[11px] uppercase tracking-[.28em] text-cyan-300">Phase 06 · Authority Completion</p><h1 className="mt-2 text-4xl font-semibold">Agent Passport & Authority</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">Passport, capability, permission, policy, risk, approval and audit evidence are shown from the authoritative backend. Presentation never grants authority.</p></div><button onClick={()=>void load()} className={btn}>Refresh</button></header>
  {error&&<div className="mt-6 rounded-xl border border-red-400/20 bg-red-500/10 p-4 text-sm text-red-200">{error}</div>}
  {!authority?<p className="mt-8 text-sm text-slate-500">Loading authoritative Agent authority…</p>:<>
   <div className="mt-8 grid gap-5 lg:grid-cols-2">
    <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Passport</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["Name",authority.agent?.name],["Status",authority.agent?.status],["Runtime",authority.agent?.runtime_state],["Verification",authority.passport?.verification_status],["Passport Updated",authority.passport?.updated_at],["Policy Version",authority.agent?.authority_policy_version]].map(([k,v])=><div key={String(k)} className="rounded-xl border border-white/10 p-4"><p className="text-[10px] uppercase tracking-wider text-slate-500">{k}</p><p className="mt-1 text-sm text-slate-200">{String(v??"—")}</p></div>)}</div><button disabled={busy||authority.passport?.verification_status==="pending"} onClick={()=>void verify()} className="mt-4 rounded-xl bg-cyan-300 px-4 py-2 text-xs font-semibold text-slate-950">{authority.passport?.verification_status==="pending"?"Verification Pending":"Request Verification"}</button></section>
    <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Policy & Budget</h2><pre className="mt-4 max-h-64 overflow-auto rounded-xl border border-white/10 bg-black/20 p-4 text-xs text-slate-400">{JSON.stringify({policy:authority.policy,budget:authority.budget},null,2)}</pre></section>
   </div>
   <div className="mt-5 grid gap-5 lg:grid-cols-2">
    <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Capabilities</h2><form onSubmit={addCapability} className="mt-4 flex gap-2"><input value={capability} onChange={e=>setCapability(e.target.value)} className={input} placeholder="Capability key"/><button disabled={busy||!capability.trim()} className="rounded-xl bg-white px-4 py-2 text-xs font-semibold text-slate-950">Grant</button></form><div className="mt-4 space-y-2">{authority.capabilities.length===0?<p className="text-sm text-slate-500">No capability records.</p>:authority.capabilities.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><div><p className="text-sm">{x.capability}</p><p className="text-[10px] text-slate-500">{x.enabled?"Active capability":"Disabled capability"}</p></div><button disabled={busy} onClick={()=>void toggleCapability(x.id,!x.enabled)} className={btn}>{x.enabled?"Disable":"Enable"}</button></div>)}</div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Permissions</h2><form onSubmit={addPermission} className="mt-4 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input value={resource} onChange={e=>setResource(e.target.value)} className={input} placeholder="Resource"/><input value={action} onChange={e=>setAction(e.target.value)} className={input} placeholder="Action"/><button disabled={busy||!resource.trim()||!action.trim()} className="rounded-xl bg-white px-4 py-2 text-xs font-semibold text-slate-950">Allow</button></form><div className="mt-4 space-y-2">{authority.permissions.length===0?<p className="text-sm text-slate-500">No permission records.</p>:authority.permissions.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 p-3"><div><p className="text-sm">{x.resource} · {x.action}</p><p className="text-[10px] text-slate-500">{x.effect} · {x.valid_until?"revoked/expired":"active"}</p></div>{!x.valid_until&&<button disabled={busy} onClick={()=>void revokePermission(x.id)} className={btn}>Revoke</button>}</div>)}</div></section>
   </div>
   <div className="mt-5 grid gap-5 xl:grid-cols-3">
    <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Risk</h2><div className="mt-4 space-y-2">{authority.risk_assessments.length===0?<p className="text-sm text-slate-500">No risk assessments yet.</p>:authority.risk_assessments.slice(0,10).map(x=><div key={x.id} className="rounded-xl border border-white/10 p-3"><p className="text-sm">{x.action} · {x.risk_level}</p><p className="text-[10px] text-slate-500">{x.decision} · {x.created_at}</p></div>)}</div></section>
    <section className="rounded-2xl border border-white/[.1] bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Approvals</h2><div className="mt-4 space-y-2">{authority.approval_requests.length===0?<p className="text-sm text-slate-500">No approval requests yet.</p>:authority.approval_requests.slice(0,10).map(x=><div key={x.id} className="rounded-xl border border-white/10 p-3"><p className="text-sm">{x.action} · {x.risk_level}</p><p className="text-[10px] text-slate-500">{x.status} · {x.created_at}</p>{x.status==="pending"&&x.resource_id&&<div className="mt-3 flex gap-2"><button disabled={busy} onClick={()=>void decide(x.resource_id,"approved")} className={btn}>Approve</button><button disabled={busy} onClick={()=>void decide(x.resource_id,"rejected")} className={btn}>Reject</button></div>}</div>)}</div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="text-xl font-semibold">Audit Evidence</h2><div className="mt-4 space-y-2">{authority.audit_logs.length===0?<p className="text-sm text-slate-500">No audit records yet.</p>:authority.audit_logs.slice(0,10).map(x=><div key={x.id} className="rounded-xl border border-white/10 p-3"><p className="text-sm">{x.action} · {x.outcome}</p><p className="text-[10px] text-slate-500">{x.resource_type} · {x.created_at}</p></div>)}</div></section>
   </div>
  </>}
 </div></main>;
}
