"use client";
import { FormEvent, useEffect, useState } from "react";
import { apiFetch } from "../lib/api";
type AgentService={agent_id:string;agent_name:string;agent_handle:string|null;owner_user_id:string;skill_name:string;skill_description:string|null;skill_configuration:Record<string,unknown>;skill_risk_level:string};
export default function AgentServiceAction({contentId,contentContext}:{contentId:string;contentContext?:Record<string,unknown>}){
 const [open,setOpen]=useState(false),[services,setServices]=useState<AgentService[]>([]),[skill,setSkill]=useState(""),[agent,setAgent]=useState(""),[prompt,setPrompt]=useState(""),[mode,setMode]=useState<"answer"|"generate_content">("answer"),[busy,setBusy]=useState(false),[result,setResult]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
 async function load(nextSkill?:string){try{const suffix=nextSkill?"?skill="+encodeURIComponent(nextSkill):"";const r=await apiFetch<{data:AgentService[]}>("/api/v1/messaging/agent-services"+suffix);setServices(r.data??[]);if(r.data?.[0]){setAgent(r.data[0].agent_id);setSkill(nextSkill||r.data[0].skill_name)}}catch(e){setError(e instanceof Error?e.message:"AGENT_SERVICE_DISCOVERY_FAILED")}}
 useEffect(()=>{if(open)void load()},[open]);
 async function submit(e:FormEvent){e.preventDefault();if(!agent||!skill||!prompt.trim())return;setBusy(true);setError(null);setResult(null);try{const r=await apiFetch<{data:{generation:{text:string}}}>("/api/v1/messaging/agent-services/generate",{method:"POST",body:JSON.stringify({agent_id:agent,skill_name:skill,prompt,mode,source_content_id:contentId,source_context:contentContext??{surface:"content"},idempotency_key:"content-service-"+crypto.randomUUID()})});setResult(r.data.generation.text);setPrompt("")}catch(e){setError(e instanceof Error?e.message:"AGENT_SERVICE_GENERATION_FAILED")}finally{setBusy(false)}}
 return <section className="mt-6 rounded-2xl border border-cyan-200/40 bg-cyan-50/50 p-4 text-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.18em] text-cyan-700">Ask an Agent</p><p className="mt-1 text-sm text-slate-700">Ask a public AI Agent about this Content, or ask it to generate related Content. AI Credits are attributed to the Agent Owner on successful generation.</p></div><button onClick={()=>setOpen(v=>!v)} className="rounded-xl bg-slate-950 px-4 py-2 text-xs text-white">{open?"Close":"Ask / Generate"}</button></div>{open&&<form onSubmit={submit} className="mt-4 grid gap-3"><div className="grid gap-3 sm:grid-cols-3"><select value={skill} onChange={e=>{setSkill(e.target.value);setAgent("");void load(e.target.value)}} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">Skill</option>{Array.from(new Set(services.map(s=>s.skill_name))).map(s=><option key={s}>{s}</option>)}</select><select value={agent} onChange={e=>setAgent(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="">Agent</option>{services.filter(s=>!skill||s.skill_name===skill).map(s=><option key={s.agent_id} value={s.agent_id}>{s.agent_name} · {s.skill_name}</option>)}</select><select value={mode} onChange={e=>setMode(e.target.value as "answer"|"generate_content")} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"><option value="answer">Ask / Explain</option><option value="generate_content">Generate Content</option></select></div><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4} placeholder="Contoh: Jelaskan Content ini dengan cara yang mudah dipahami… atau buatkan versi carousel…" className="rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm"/><button disabled={busy||!agent||!skill||!prompt.trim()} className="rounded-xl bg-slate-950 px-4 py-3 text-sm text-white disabled:opacity-40">{busy?"Generating…":"Run Agent Service"}</button>{error&&<p className="text-xs text-red-700">{error}</p>}{result&&<div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs uppercase tracking-wider text-slate-500">Agent Result</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{result}</p></div>}</form>}</section>
}