"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
type Booth={id:string;district_id:string;name:string;slug:string;tier:string;status:string;moderation_status:string;theme_key:string|null;booth_type:string};
export default function BoothsSurface(){
 const[b,setB]=useState<Booth[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[districtId,setDistrictId]=useState(""),[name,setName]=useState(""),[slug,setSlug]=useState(""),[type,setType]=useState("personal"),[tier,setTier]=useState("free"),[theme,setTheme]=useState("");
 async function load(){setLoading(true);setError(null);try{const r=await apiFetch<{data:Booth[]}>(districtId?"/api/v1/booths?district_id="+encodeURIComponent(districtId):"/api/v1/booths");setB(r.data||[])}catch(e){setError(e instanceof Error?e.message:"BOOTH_LOAD_FAILED")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{await apiFetch("/api/v1/booths",{method:"POST",body:JSON.stringify({district_id:districtId,name,slug,booth_type:type,tier,theme_key:theme||null})});setName("");setSlug("");await load()}catch(e){setError(e instanceof Error?e.message:"BOOTH_CREATE_FAILED")}finally{setBusy(false)}}
 async function submit(id:string){setBusy(true);try{await apiFetch("/api/v1/booths/"+id+"/submit",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"BOOTH_SUBMIT_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl"><header className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 20</p><h1 className="mt-2 text-4xl font-semibold">Booth / Tenant</h1><p className="mt-3 max-w-3xl text-slate-400">Spatial tenant inside a District: identity, theme, 3D scene, catalog, presentation, media and a declarative entry point for Phase 22 Live Experiences.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Refresh</button></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Create Booth</h2><p className="mt-2 text-sm text-slate-500">District access and paid-tier entitlement are evaluated by the backend. Theme compatibility is checked against the District.</p><form onSubmit={create} className="mt-4 grid gap-3"><input value={districtId} onChange={e=>setDistrictId(e.target.value)} placeholder="District UUID" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Booth name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="booth-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["personal","creator","agent","business","store","office","studio","community_space","event_venue","collaboration_space"].map(x=><option key={x}>{x}</option>)}</select><select value={tier} onChange={e=>setTier(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["free","standard","creator","business","prime","event","enterprise"].map(x=><option key={x}>{x}</option>)}</select><input value={theme} onChange={e=>setTheme(e.target.value)} placeholder="Theme key (optional)" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><button disabled={busy} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Create Booth</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Accessible Booths</h2><span className="text-xs text-slate-500">{b.length} visible</span></div>{b.length===0?<p className="mt-4 text-sm text-slate-500">{loading?"Loading…":"No accessible booths."}</p>:<div className="mt-4 space-y-2">{b.map(x=><article key={x.id} className="rounded-xl border border-white/10 p-4"><div className="flex justify-between gap-3"><span>{x.name}</span><span className="text-xs uppercase text-slate-500">{x.status}</span></div><p className="mt-1 text-xs text-slate-500">{x.booth_type} · {x.tier} · moderation: {x.moderation_status}{x.theme_key?" · "+x.theme_key:""}</p><p className="mt-1 break-all text-[11px] text-slate-600">{x.id}</p>{x.status==="draft"&&<button disabled={busy} onClick={()=>void submit(x.id)} className="mt-3 rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-40">Submit for moderation</button>}</article>)}</div>}</section></div></div></main>}
