"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
type District={id:string;world_id:string;name:string;slug:string;district_type:string;visibility:string;status:string;theme_key:string|null};
export default function DistrictsSurface(){
 const[d,setD]=useState<District[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[worldId,setWorldId]=useState(""),[name,setName]=useState(""),[slug,setSlug]=useState(""),[type,setType]=useState("general"),[visibility,setVisibility]=useState("public"),[selected,setSelected]=useState<District|null>(null);
 async function load(){setLoading(true);setError(null);try{const r=await apiFetch<{data:District[]}>(worldId?"/api/v1/districts?world_id="+encodeURIComponent(worldId):"/api/v1/districts");setD(r.data||[])}catch(e){setError(e instanceof Error?e.message:"DISTRICT_LOAD_FAILED")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{await apiFetch("/api/v1/districts",{method:"POST",body:JSON.stringify({world_id:worldId,name,slug,district_type:type,visibility})});setName("");setSlug("");await load()}catch(e){setError(e instanceof Error?e.message:"DISTRICT_CREATE_FAILED")}finally{setBusy(false)}}
 async function publish(id:string){setBusy(true);try{await apiFetch("/api/v1/districts/"+id+"/publish",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"DISTRICT_PUBLISH_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl"><header className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 19</p><h1 className="mt-2 text-4xl font-semibold">Districts</h1><p className="mt-3 max-w-3xl text-slate-400">World segmentation, membership, entitlement and fail-closed access boundaries. Enterprise access is evaluated server-side.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Refresh</button></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2">
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Create District</h2><p className="mt-2 text-sm text-slate-500">Requires an active World you own or are authorized to manage.</p><form onSubmit={create} className="mt-4 grid gap-3"><input value={worldId} onChange={e=>setWorldId(e.target.value)} placeholder="World UUID" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={name} onChange={e=>setName(e.target.value)} placeholder="District name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="district-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["general","investor","founder","owner","director","pitching","creator","commerce","event","enterprise","private"].map(x=><option key={x}>{x}</option>)}</select><select value={visibility} onChange={e=>setVisibility(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["public","restricted","private","enterprise"].map(x=><option key={x}>{x}</option>)}</select><button disabled={busy} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Create District</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Accessible Districts</h2><span className="text-xs text-slate-500">{d.length} visible</span></div>{d.length===0?<p className="mt-4 text-sm text-slate-500">{loading?"Loading…":"No accessible districts."}</p>:<div className="mt-4 space-y-2">{d.map(x=><button key={x.id} onClick={()=>setSelected(x)} className="w-full rounded-xl border border-white/10 p-4 text-left"><div className="flex justify-between gap-3"><span>{x.name}</span><span className="text-xs uppercase text-slate-500">{x.status}</span></div><p className="mt-1 text-xs text-slate-500">{x.district_type} · {x.visibility}{x.theme_key?" · "+x.theme_key:""}</p><p className="mt-1 break-all text-[11px] text-slate-600">{x.id}</p></button>)}</div>}</section>
 {selected&&<section className="lg:col-span-2 rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">Visibility: {selected.visibility} · Type: {selected.district_type}</p></div><button disabled={busy||selected.status!=="draft"} onClick={()=>void publish(selected.id)} className="rounded-xl border border-white/10 px-4 py-2 text-sm disabled:opacity-40">Publish</button></div><p className="mt-4 text-sm text-slate-400">Membership, access requests, entitlements and zones are available through the authenticated District API and remain empty until real actors perform those actions.</p></section>}
 </div></div></main>
}