"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api";

type District={id:string;world_id:string;name:string;slug:string;district_type:string;visibility:string;status:string;theme_key:string|null};
type Zone={id:string;district_id:string;zone_key:string;name:string;zone_type:string;status:string};
type World={id:string;name:string;slug:string;status:string;theme_key:string|null};

export default function DistrictsSurface(){
 const[d,setD]=useState<District[]>([]),[worlds,setWorlds]=useState<World[]>([]),[zones,setZones]=useState<Zone[]>([]);
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[worldId,setWorldId]=useState(""),[name,setName]=useState(""),[slug,setSlug]=useState(""),[type,setType]=useState("general"),[visibility,setVisibility]=useState("public");
 const[zoneKey,setZoneKey]=useState(""),[zoneName,setZoneName]=useState(""),[zoneType,setZoneType]=useState("public"),[selected,setSelected]=useState<District|null>(null);
 async function load(){setLoading(true);setError(null);try{const [dr,wr]=await Promise.all([apiFetch<{data:District[]}>(worldId?"/api/v1/districts?world_id="+encodeURIComponent(worldId):"/api/v1/districts"),apiFetch<{data:World[]}>("/api/v1/universe/worlds")]);setD(dr.data||[]);setWorlds(wr.data||[])}catch(e){setError(e instanceof Error?e.message:"DISTRICT_LOAD_FAILED")}finally{setLoading(false)}}
 async function loadZones(id:string){try{const r=await apiFetch<{data:Zone[]}>("/api/v1/districts/"+id+"/zones");setZones(r.data||[])}catch(e){setError(e instanceof Error?e.message:"ZONE_LOAD_FAILED")}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{await apiFetch("/api/v1/districts",{method:"POST",body:JSON.stringify({world_id:worldId,name,slug,district_type:type,visibility})});setName("");setSlug("");await load()}catch(e){setError(e instanceof Error?e.message:"DISTRICT_CREATE_FAILED")}finally{setBusy(false)}}
 async function createZone(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError(null);try{await apiFetch("/api/v1/districts/"+selected.id+"/zones",{method:"POST",body:JSON.stringify({zone_key:zoneKey,name:zoneName,zone_type:zoneType,spatial_config:{presentation_only:true},metadata:{}})});setZoneKey("");setZoneName("");await loadZones(selected.id)}catch(e){setError(e instanceof Error?e.message:"ZONE_CREATE_FAILED")}finally{setBusy(false)}}
 async function publish(id:string){setBusy(true);try{await apiFetch("/api/v1/districts/"+id+"/publish",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"DISTRICT_PUBLISH_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl">
 <header className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 19</p><h1 className="mt-2 text-4xl font-semibold">Districts</h1><p className="mt-3 max-w-3xl text-slate-400">Authoritative World → District → Zone provisioning. No synthetic records are created.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Refresh</button></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2">
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Create District</h2><p className="mt-2 text-sm text-slate-500">World must already exist and be authorized by the backend.</p><form onSubmit={create} className="mt-4 grid gap-3">
 <select value={worldId} onChange={e=>setWorldId(e.target.value)} required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">Select existing World</option>{worlds.map(w=><option key={w.id} value={w.id}>{w.name} · {w.status}</option>)}</select>
 <input value={name} onChange={e=>setName(e.target.value)} placeholder="District name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="district-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/>
 <select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["general","investor","founder","owner","director","pitching","creator","commerce","event","enterprise","private"].map(x=><option key={x}>{x}</option>)}</select>
 <select value={visibility} onChange={e=>setVisibility(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["public","restricted","private","enterprise"].map(x=><option key={x}>{x}</option>)}</select>
 <button disabled={busy||!worldId} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Create District</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Accessible Districts</h2><span className="text-xs text-slate-500">{d.length} visible</span></div>{d.length===0?<p className="mt-4 text-sm text-slate-500">{loading?"Loading…":"No accessible districts."}</p>:<div className="mt-4 space-y-2">{d.map(x=><button key={x.id} onClick={()=>{setSelected(x);void loadZones(x.id)}} className="w-full rounded-xl border border-white/10 p-4 text-left"><div className="flex justify-between gap-3"><span>{x.name}</span><span className="text-xs uppercase text-slate-500">{x.status}</span></div><p className="mt-1 text-xs text-slate-500">{x.district_type} · {x.visibility}{x.theme_key?" · "+x.theme_key:""}</p><p className="mt-1 break-all text-[11px] text-slate-600">{x.id}</p></button>)}</div>}</section>
 {selected&&<section className="lg:col-span-2 rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">Zone provisioning is authoritative and persisted through FastAPI → Supabase.</p></div><button disabled={busy||selected.status!=="draft"} onClick={()=>void publish(selected.id)} className="rounded-xl border border-white/10 px-4 py-2 text-sm disabled:opacity-40">Publish</button></div>
 <form onSubmit={createZone} className="mt-5 grid gap-3 sm:grid-cols-4"><input value={zoneKey} onChange={e=>setZoneKey(e.target.value)} placeholder="zone-key" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={zoneName} onChange={e=>setZoneName(e.target.value)} placeholder="Zone name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><select value={zoneType} onChange={e=>setZoneType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["public","member","restricted","enterprise","private"].map(x=><option key={x}>{x}</option>)}</select><button disabled={busy} className="rounded-xl bg-cyan-300 px-4 py-3 text-sm font-medium text-slate-950">Create Zone</button></form>
 <div className="mt-5 grid gap-2 sm:grid-cols-2">{zones.length===0?<p className="text-sm text-slate-500">No real Zones yet.</p>:zones.map(z=><div key={z.id} className="rounded-xl border border-white/10 p-4"><div className="flex justify-between"><span>{z.name}</span><span className="text-xs text-slate-500">{z.status}</span></div><p className="mt-1 text-xs text-slate-500">{z.zone_key} · {z.zone_type}</p></div>)}</div></section>}
 </div></div></main>
}