"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
import AgentAccountCard, { AgentAccount } from "./agent-account-card";

type District={id:string;world_id:string;name:string;slug:string;district_type:string;visibility:string;status:string;theme_key:string|null};
type Zone={id:string;district_id:string;zone_key:string;name:string;zone_type:string;status:string};
type SpatialObject={id:string;district_id:string;zone_id:string|null;object_type:string;name:string;slug:string;status:string;capacity:number|null;availability:string};
type World={id:string;name:string;slug:string;status:string;theme_key:string|null};
type Booth={id:string;name:string;slug:string;tier:string;booth_type:string;status:string;moderation_status:string;district_id:string;district_zone_id:string|null;theme_key:string|null};

const objectTypes=["building","road","coworking","meeting_room","event","marketplace","agent_zone","community_zone"];

export default function DistrictsSurface(){
 const[d,setD]=useState<District[]>([]),[worlds,setWorlds]=useState<World[]>([]),[zones,setZones]=useState<Zone[]>([]),[objects,setObjects]=useState<SpatialObject[]>([]),[districtAgents,setDistrictAgents]=useState<AgentAccount[]>([]),[booths,setBooths]=useState<Booth[]>([]);
 const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[requests,setRequests]=useState<any[]>([]),[members,setMembers]=useState<any[]>([]),[entitlements,setEntitlements]=useState<any[]>([]),[requestTier,setRequestTier]=useState("standard"),[requestReason,setRequestReason]=useState("");
 const[worldId,setWorldId]=useState(""),[name,setName]=useState(""),[slug,setSlug]=useState(""),[type,setType]=useState("general"),[visibility,setVisibility]=useState("public");
 const[zoneKey,setZoneKey]=useState(""),[zoneName,setZoneName]=useState(""),[zoneType,setZoneType]=useState("public"),[selected,setSelected]=useState<District|null>(null);
 const[objName,setObjName]=useState(""),[objSlug,setObjSlug]=useState(""),[objType,setObjType]=useState("building"),[objZone,setObjZone]=useState(""),[objCapacity,setObjCapacity]=useState(""),[objAvailability,setObjAvailability]=useState("available");

 async function load(){setLoading(true);setError(null);try{const [dr,wr]=await Promise.all([apiFetch<{data:District[]}>(worldId?"/api/v1/districts?world_id="+encodeURIComponent(worldId):"/api/v1/districts"),apiFetch<{data:World[]}>("/api/v1/universe/worlds")]);setD(dr.data||[]);setWorlds(wr.data||[])}catch(e){setError(e instanceof Error?e.message:"DISTRICT_LOAD_FAILED")}finally{setLoading(false)}}
 async function loadDistrict(id:string){try{const[z,o,a,r,m,e,b]=await Promise.all([apiFetch<{data:Zone[]}>("/api/v1/districts/"+id+"/zones"),apiFetch<{data:SpatialObject[]}>("/api/v1/districts/"+id+"/spatial-objects"),apiFetch<{data:AgentAccount[]}>("/api/v1/agent-catalog/accounts?district_id="+encodeURIComponent(id)+"&limit=12"),apiFetch<{data:any[]}>("/api/v1/districts/"+id+"/requests"),apiFetch<{data:any[]}>("/api/v1/districts/"+id+"/members"),apiFetch<{data:any[]}>("/api/v1/districts/"+id+"/entitlements"),apiFetch<{data:Booth[]}>("/api/v1/booths?district_id="+encodeURIComponent(id)+"&limit=100")]);setZones(z.data||[]);setObjects(o.data||[]);setDistrictAgents(a.data||[]);setBooths(b.data||[]);setRequests(r.data||[]);setMembers(m.data||[]);setEntitlements(e.data||[])}catch(e){setError(e instanceof Error?e.message:"DISTRICT_DETAIL_LOAD_FAILED")}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{await apiFetch("/api/v1/districts",{method:"POST",body:JSON.stringify({world_id:worldId,name,slug,district_type:type,visibility})});setName("");setSlug("");await load()}catch(e){setError(e instanceof Error?e.message:"DISTRICT_CREATE_FAILED")}finally{setBusy(false)}}
 async function createZone(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError(null);try{await apiFetch("/api/v1/districts/"+selected.id+"/zones",{method:"POST",body:JSON.stringify({zone_key:zoneKey,name:zoneName,zone_type:zoneType,spatial_config:{presentation_only:true},metadata:{}})});setZoneKey("");setZoneName("");await loadDistrict(selected.id)}catch(e){setError(e instanceof Error?e.message:"ZONE_CREATE_FAILED")}finally{setBusy(false)}}
 async function activateZone(id:string){setBusy(true);try{await apiFetch("/api/v1/districts/zones/"+id+"/activate",{method:"POST"});if(selected)await loadDistrict(selected.id)}catch(e){setError(e instanceof Error?e.message:"ZONE_ACTIVATE_FAILED")}finally{setBusy(false)}}
 async function createObject(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError(null);try{await apiFetch("/api/v1/districts/"+selected.id+"/spatial-objects",{method:"POST",body:JSON.stringify({zone_id:objZone||null,object_type:objType,name:objName,slug:objSlug,capacity:objCapacity?Number(objCapacity):null,availability:objAvailability,spatial_config:{presentation_only:true},presentation_config:{renderer:"AllphaWorldRenderer"},metadata:{}})});setObjName("");setObjSlug("");setObjCapacity("");await loadDistrict(selected.id)}catch(e){setError(e instanceof Error?e.message:"SPATIAL_OBJECT_CREATE_FAILED")}finally{setBusy(false)}}
 async function join(){if(!selected)return;setBusy(true);setError(null);try{await apiFetch("/api/v1/districts/"+selected.id+"/join",{method:"POST",body:JSON.stringify({subject_type:"user"})});await loadDistrict(selected.id)}catch(e){setError(e instanceof Error?e.message:"DISTRICT_JOIN_FAILED")}finally{setBusy(false)}}
 async function requestAccess(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError(null);try{await apiFetch("/api/v1/districts/"+selected.id+"/requests",{method:"POST",body:JSON.stringify({requester_type:"user",requested_tier:requestTier,reason:requestReason})});setRequestReason("");await loadDistrict(selected.id)}catch(e){setError(e instanceof Error?e.message:"DISTRICT_ACCESS_REQUEST_FAILED")}finally{setBusy(false)}}
 async function decideAccess(id:string,decision:string){if(!selected)return;setBusy(true);setError(null);try{await apiFetch("/api/v1/districts/requests/"+id+"/decision",{method:"POST",body:JSON.stringify({decision,role:"member"})});await loadDistrict(selected.id)}catch(e){setError(e instanceof Error?e.message:"DISTRICT_ACCESS_DECISION_FAILED")}finally{setBusy(false)}}

 async function activateObject(id:string){setBusy(true);try{await apiFetch("/api/v1/districts/spatial-objects/"+id+"/activate",{method:"POST"});if(selected)await loadDistrict(selected.id)}catch(e){setError(e instanceof Error?e.message:"SPATIAL_OBJECT_ACTIVATE_FAILED")}finally{setBusy(false)}}
 async function publish(id:string){setBusy(true);try{await apiFetch("/api/v1/districts/"+id+"/publish",{method:"POST"});await load();const next=d.find(x=>x.id===id);if(next)setSelected({...next,status:"active"})}catch(e){setError(e instanceof Error?e.message:"DISTRICT_PUBLISH_FAILED")}finally{setBusy(false)}}

 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl">
 <header className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 19</p><h1 className="mt-2 text-4xl font-semibold">Districts</h1><p className="mt-3 max-w-3xl text-slate-400">Living World → District → Zone → spatial object layer. Authority remains server-side; presentation uses the canonical World Renderer.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Refresh</button></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2">
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Create District</h2><p className="mt-2 text-sm text-slate-500">World must already exist and be authorized by the backend.</p><form onSubmit={create} className="mt-4 grid gap-3">
 <select value={worldId} onChange={e=>setWorldId(e.target.value)} required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">Select existing World</option>{worlds.map(w=><option key={w.id} value={w.id}>{w.name} · {w.status}</option>)}</select>
 <input value={name} onChange={e=>setName(e.target.value)} placeholder="District name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="district-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/>
 <select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["general","investor","founder","owner","director","pitching","creator","commerce","event","enterprise","private"].map(x=><option key={x}>{x}</option>)}</select>
 <select value={visibility} onChange={e=>setVisibility(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["public","restricted","private","enterprise"].map(x=><option key={x}>{x}</option>)}</select>
 <button disabled={busy||!worldId} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Create District</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Accessible Districts</h2><span className="text-xs text-slate-500">{d.length} visible</span></div>{d.length===0?<p className="mt-4 text-sm text-slate-500">{loading?"Loading…":"No accessible districts."}</p>:<div className="mt-4 space-y-2">{d.map(x=><button key={x.id} onClick={()=>{setSelected(x);void loadDistrict(x.id)}} className="w-full rounded-xl border border-white/10 p-4 text-left"><div className="flex justify-between gap-3"><span>{x.name}</span><span className="text-xs uppercase text-slate-500">{x.status}</span></div><p className="mt-1 text-xs text-slate-500">{x.district_type} · {x.visibility}{x.theme_key?" · "+x.theme_key:""}</p></button>)}</div>}</section>
 {selected&&<section className="lg:col-span-2 rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">Zones and spatial objects are authoritative records persisted through FastAPI → Supabase.</p></div><button disabled={busy||selected.status!=="draft"} onClick={()=>void publish(selected.id)} className="rounded-xl border border-white/10 px-4 py-2 text-sm disabled:opacity-40">Publish</button></div>
 {selected&&<div className="mb-6 rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase tracking-[.2em] text-cyan-300">Agent Presence → Agent Account</p><h3 className="mt-1 text-lg font-semibold">Agents in this District</h3>{districtAgents.length===0?<p className="mt-3 text-sm text-slate-500">Belum ada Agent yang memiliki spatial presence aktif di District ini.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{districtAgents.map(a=><AgentAccountCard key={a.agent_id} agent={a} compact discoveryContext={{source_surface:"district",district_id:selected.id}} />)}</div>}</div>}
 <div className="mt-5 rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.2em] text-cyan-300">District → Booth</p><h3 className="mt-1 text-lg font-semibold">Tenant / Venue Composition</h3></div><a href="/booths" className="text-xs text-slate-400">Open Booth Builder</a></div><p className="mt-2 text-sm text-slate-500">Booth records are read through the same authoritative District scope; no duplicate tenant state is created here.</p>{booths.length===0?<p className="mt-4 text-xs text-slate-500">Belum ada Booth real di District ini.</p>:<div className="mt-4 grid gap-2 md:grid-cols-2 lg:grid-cols-3">{booths.map(b=><a key={b.id} href="/booths" className="rounded-xl border border-white/10 p-3"><div className="flex justify-between gap-2"><span>{b.name}</span><span className="text-xs text-slate-500">{b.status}</span></div><p className="mt-1 text-xs text-slate-500">{b.booth_type} · {b.tier}{b.district_zone_id?" · Zone-bound":""}</p></a>)}</div>}</div><div className="mt-5 grid gap-6 xl:grid-cols-3">
 <section className="rounded-2xl border border-white/10 p-4"><div className="flex items-center justify-between"><h3 className="text-sm font-medium">Membership / Access</h3><button disabled={busy} onClick={()=>void join()} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Join</button></div><p className="mt-2 text-xs text-slate-500">{members.length} membership record(s)</p><div className="mt-3 space-y-2">{members.length===0?<p className="text-xs text-slate-500">No memberships.</p>:members.slice(0,6).map(m=><div key={m.id} className="rounded-lg border border-white/10 p-2 text-xs"><div className="flex justify-between"><span>{m.subject_type}</span><span>{m.status}</span></div><p className="mt-1 text-slate-500">{m.role||"member"}</p></div>)}</div></section>
 <section className="rounded-2xl border border-white/10 p-4"><h3 className="text-sm font-medium">Access Request</h3><form onSubmit={requestAccess} className="mt-3 grid gap-2"><select value={requestTier} onChange={e=>setRequestTier(e.target.value)} className="rounded-lg border border-white/10 bg-black/20 p-2 text-xs">{["standard","creator","business","enterprise"].map(x=><option key={x}>{x}</option>)}</select><textarea value={requestReason} onChange={e=>setRequestReason(e.target.value)} placeholder="Reason (optional)" className="min-h-16 rounded-lg border border-white/10 bg-black/20 p-2 text-xs"/><button disabled={busy} className="rounded-lg bg-white px-3 py-2 text-xs text-black">Request Access</button></form><div className="mt-3 space-y-2">{requests.slice(0,6).map(r=><div key={r.id} className="rounded-lg border border-white/10 p-2 text-xs"><div className="flex justify-between"><span>{r.requested_tier}</span><span>{r.status}</span></div>{r.status==="pending"&&<div className="mt-2 flex gap-2"><button disabled={busy} onClick={()=>void decideAccess(r.id,"approved")} className="rounded border border-white/10 px-2 py-1">Approve</button><button disabled={busy} onClick={()=>void decideAccess(r.id,"rejected")} className="rounded border border-white/10 px-2 py-1">Reject</button></div>}</div>)}</div></section>
 <section className="rounded-2xl border border-white/10 p-4"><h3 className="text-sm font-medium">Entitlements</h3><p className="mt-2 text-xs text-slate-500">{entitlements.length} authoritative entitlement(s)</p><div className="mt-3 space-y-2">{entitlements.length===0?<p className="text-xs text-slate-500">No entitlements.</p>:entitlements.slice(0,8).map(e=><div key={e.id} className="rounded-lg border border-white/10 p-2 text-xs"><div className="flex justify-between"><span>{e.tier}</span><span>{e.entitlement_key}</span></div><p className="mt-1 text-slate-500">{e.status||"active"}</p></div>)}</div></section>
 </div>
 <div className="mt-5 grid gap-6 xl:grid-cols-2">
 <div><h3 className="text-sm font-medium">Zones</h3><form onSubmit={createZone} className="mt-3 grid gap-3 sm:grid-cols-4"><input value={zoneKey} onChange={e=>setZoneKey(e.target.value)} placeholder="zone-key" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={zoneName} onChange={e=>setZoneName(e.target.value)} placeholder="Zone name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><select value={zoneType} onChange={e=>setZoneType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["public","member","restricted","enterprise","private"].map(x=><option key={x}>{x}</option>)}</select><button disabled={busy} className="rounded-xl bg-cyan-300 px-4 py-3 text-sm font-medium text-slate-950">Create Zone</button></form>
 <div className="mt-4 grid gap-2">{zones.length===0?<p className="text-sm text-slate-500">No real Zones yet.</p>:zones.map(z=><div key={z.id} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><div><span>{z.name}</span><p className="text-xs text-slate-500">{z.zone_key} · {z.zone_type}</p></div>{z.status==="draft"&&<button onClick={()=>void activateZone(z.id)} disabled={busy} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Activate</button>}</div>)}</div></div>
 <div><h3 className="text-sm font-medium">Spatial Objects</h3><form onSubmit={createObject} className="mt-3 grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><input value={objName} onChange={e=>setObjName(e.target.value)} placeholder="Object name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={objSlug} onChange={e=>setObjSlug(e.target.value)} placeholder="object-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><div className="grid gap-3 sm:grid-cols-3"><select value={objType} onChange={e=>setObjType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{objectTypes.map(x=><option key={x}>{x}</option>)}</select><select value={objZone} onChange={e=>setObjZone(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">No zone</option>{zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select><input value={objCapacity} onChange={e=>setObjCapacity(e.target.value)} type="number" min="0" placeholder="Capacity" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><div className="grid gap-3 sm:grid-cols-2"><select value={objAvailability} onChange={e=>setObjAvailability(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["available","limited","reserved","unavailable"].map(x=><option key={x}>{x}</option>)}</select><button disabled={busy||selected.status!=="draft"&&selected.status!=="active"} className="rounded-xl bg-white px-4 py-3 text-sm text-black">Create Spatial Object</button></div></form>
 <div className="mt-4 grid gap-2">{objects.length===0?<p className="text-sm text-slate-500">No real spatial objects yet.</p>:objects.map(o=><div key={o.id} className="flex items-center justify-between rounded-xl border border-white/10 p-3"><div><span>{o.name}</span><p className="text-xs text-slate-500">{o.object_type} · {o.availability}{o.capacity!==null?" · cap "+o.capacity:""}</p></div>{o.status==="draft"&&<button onClick={()=>void activateObject(o.id)} disabled={busy} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Activate</button>}</div>)}</div></div>
 </div></section>}
 </div></div></main>
}