"use client";
import { FormEvent,useEffect,useState } from "react";
import { apiFetch } from "../lib/api";

type Workflow={id:string;name:string;slug:string;status:string;description?:string|null};
type Mission={id:string;workflow_id:string;name:string;description?:string|null;status:string;visibility:string;join_policy:string;max_participants?:number|null;created_at:string};
type Participant={id:string;subject_type:string;subject_id:string;status:string;created_at:string};

export default function MissionSurface(){
 const [workflows,setWorkflows]=useState<Workflow[]>([]),[missions,setMissions]=useState<Mission[]>([]),[selected,setSelected]=useState<Mission|null>(null),[participants,setParticipants]=useState<Participant[]>([]);
 const [workflowId,setWorkflowId]=useState(""),[name,setName]=useState(""),[description,setDescription]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 async function load(){setError(null);try{const [w,m]=await Promise.all([apiFetch<{data:Workflow[]}>("/api/v1/workflows?limit=100"),apiFetch<{data:Mission[]}>("/api/v1/workflows/missions?limit=100")]);setWorkflows(w.data??[]);setMissions(m.data??[])}catch(e){setError(e instanceof Error?e.message:"MISSION_LOAD_FAILED")}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();if(!workflowId||!name.trim())return;setBusy(true);try{await apiFetch("/api/v1/workflows/missions",{method:"POST",body:JSON.stringify({workflow_id:workflowId,name:name.trim(),description:description.trim()||null,visibility:"public",join_policy:"open"})});setName("");setDescription("");await load()}catch(e){setError(e instanceof Error?e.message:"MISSION_CREATE_FAILED")}finally{setBusy(false)}}
 async function action(id:string,op:"publish"|"join"){setBusy(true);try{await apiFetch("/api/v1/workflows/missions/"+id+"/"+op,{method:"POST",body:op==="join"?JSON.stringify({subject_type:"user"}):undefined});await load();if(selected?.id===id)await open(id)}catch(e){setError(e instanceof Error?e.message:"MISSION_ACTION_FAILED")}finally{setBusy(false)}}
 async function open(id:string){const m=missions.find(x=>x.id===id);if(!m)return;setSelected(m);try{const r=await apiFetch<{data:Participant[]}>("/api/v1/workflows/missions/"+id+"/participants");setParticipants(r.data??[])}catch(e){setError(e instanceof Error?e.message:"MISSION_PARTICIPANTS_FAILED")}}
 async function decide(id:string,decision:"approve"|"reject"){setBusy(true);try{await apiFetch("/api/v1/workflows/missions/participants/"+id+"/decision",{method:"POST",body:JSON.stringify({decision})});if(selected)await open(selected.id)}catch(e){setError(e instanceof Error?e.message:"MISSION_DECISION_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-50 p-5 text-slate-950 sm:p-8"><div className="mx-auto max-w-7xl"><header><p className="text-xs uppercase tracking-[.24em] text-cyan-700">Workflow & Mission Engine</p><h1 className="mt-2 text-4xl font-semibold">Missions</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Mission lifecycle over the existing Workflow and Agent Runtime. No mission data is fabricated; empty states reflect the authoritative database.</p></header>{error&&<div className="mt-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Create Mission</h2>{workflows.length===0?<p className="mt-3 text-sm text-slate-500">No Workflow is available yet. Create and publish a Workflow first.</p>:<form onSubmit={create} className="mt-4 grid gap-3"><select value={workflowId} onChange={e=>setWorkflowId(e.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select published/available Workflow</option>{workflows.map(w=><option key={w.id} value={w.id}>{w.name} · {w.status}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Mission name" className="rounded-xl border border-slate-200 px-4 py-3 text-sm"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Mission description" rows={3} className="rounded-xl border border-slate-200 px-4 py-3 text-sm"/><button disabled={busy||!workflowId||!name.trim()} className="w-fit rounded-xl bg-slate-950 px-5 py-3 text-sm font-medium text-white disabled:opacity-40">Create Mission</button></form>}</section>
 <div className="mt-8 grid gap-5 lg:grid-cols-2">{missions.length===0?<div className="rounded-3xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No Mission records yet.</div>:missions.map(m=><article key={m.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] uppercase tracking-[.18em] text-cyan-700">{m.status}</p><h2 className="mt-2 text-xl font-semibold">{m.name}</h2><p className="mt-2 text-sm text-slate-600">{m.description||"No description."}</p></div><span className="text-xs text-slate-500">{m.join_policy}</span></div><div className="mt-5 flex flex-wrap gap-2">{m.status==="draft"&&<button disabled={busy} onClick={()=>void action(m.id,"publish")} className="rounded-xl bg-slate-950 px-3 py-2 text-xs text-white">Publish</button>}{(m.status==="open"||m.status==="active")&&<button disabled={busy} onClick={()=>void action(m.id,"join")} className="rounded-xl border border-slate-200 px-3 py-2 text-xs">Join</button>}<button onClick={()=>void open(m.id)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs">Participants</button></div></article>)}</div>
 {selected&&<section className="mt-8 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.18em] text-cyan-700">Mission Participants</p><h2 className="mt-2 text-2xl font-semibold">{selected.name}</h2></div><button onClick={()=>setSelected(null)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs">Close</button></div><div className="mt-5 space-y-3">{participants.length===0?<p className="text-sm text-slate-500">No participants.</p>:participants.map(p=><div key={p.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-4"><div><p className="text-sm">{p.subject_type} · {p.subject_id}</p><p className="mt-1 text-xs text-slate-500">{p.status} · {p.created_at}</p></div>{p.status==="pending"&&<div className="flex gap-2"><button disabled={busy} onClick={()=>void decide(p.id,"approve")} className="rounded-lg border border-slate-200 px-3 py-2 text-xs">Approve</button><button disabled={busy} onClick={()=>void decide(p.id,"reject")} className="rounded-lg border border-red-200 px-3 py-2 text-xs text-red-700">Reject</button></div>}</div>)}</div></section>}
 </div></main>
}