"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
type Theme={id:string;name:string;slug:string;category:string;status:string;moderation_status:string};
type Version={id:string;version:number;status:string;validation_status:string;performance_status:string;moderation_status:string};
export default function ThemeBuilderSurface(){
 const[themes,setThemes]=useState<Theme[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[name,setName]=useState(""),[slug,setSlug]=useState(""),[category,setCategory]=useState(""),[selected,setSelected]=useState<Theme|null>(null),[versions,setVersions]=useState<Version[]>([]);
 async function load(){setLoading(true);setError(null);try{const r=await apiFetch<{data:Theme[]}>("/api/v1/themes");setThemes(r.data||[])}catch(e){setError(e instanceof Error?e.message:"THEME_LOAD_FAILED")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{await apiFetch("/api/v1/themes",{method:"POST",body:JSON.stringify({name,slug,category})});setName("");setSlug("");setCategory("");await load()}catch(e){setError(e instanceof Error?e.message:"THEME_CREATE_FAILED")}finally{setBusy(false)}}
 async function openTheme(t:Theme){setSelected(t);setError(null);try{const r=await apiFetch<{data:Version[]}>("/api/v1/themes/"+t.id+"/versions");setVersions(r.data||[])}catch(e){setError(e instanceof Error?e.message:"THEME_VERSION_LOAD_FAILED")}}
 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl"><header><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 21</p><h1 className="mt-2 text-4xl font-semibold">Theme Builder</h1><p className="mt-3 max-w-3xl text-slate-400">Governed Theme registry and version workflow. Presentation configuration cannot change authority or security.</p></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Create Theme Draft</h2><form onSubmit={create} className="mt-4 grid gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Theme name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="theme-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Category" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><button disabled={busy} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Create draft</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Authoritative Themes</h2><button onClick={()=>void load()} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Refresh</button></div>{themes.length===0?<p className="mt-4 text-sm text-slate-500">{loading?"Loading…":"No authoritative themes yet."}</p>:<div className="mt-4 space-y-2">{themes.map(t=><button key={t.id} onClick={()=>void openTheme(t)} className="block w-full rounded-xl border border-white/10 p-4 text-left hover:bg-white/[.03]"><div className="flex justify-between"><span>{t.name}</span><span className="text-xs text-slate-500">{t.status}</span></div><p className="mt-1 text-xs text-slate-500">{t.category} · moderation: {t.moderation_status}</p></button>)}</div>}</section></div>
 {selected&&<section className="mt-6 rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">{selected.name} — Versions</h2>{versions.length===0?<p className="mt-3 text-sm text-slate-500">No versions exist for this Theme.</p>:<div className="mt-3 space-y-2">{versions.map(v=><div key={v.id} className="rounded-xl border border-white/10 p-4 text-sm"><div className="flex justify-between"><span>Version {v.version}</span><span>{v.status}</span></div><p className="mt-1 text-xs text-slate-500">validation: {v.validation_status} · performance: {v.performance_status} · moderation: {v.moderation_status}</p></div>)}</div>}</section>}</div></main>
}