"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
type Galaxy={id:string;name:string;slug:string;status:string;visibility:string};
type World={id:string;galaxy_id:string;name:string;slug:string;status:string;visibility:string;world_type:string;theme_key:string|null};
export default function UniverseSurface(){
 const[g,setG]=useState<Galaxy[]>([]),[w,setW]=useState<World[]>([]),[sel,setSel]=useState<World|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const[gn,setGn]=useState(""),[gs,setGs]=useState(""),[galaxyId,setGalaxyId]=useState(""),[wn,setWn]=useState(""),[ws,setWs]=useState(""),[worldType,setWorldType]=useState("social");
 async function load(){setLoading(true);try{const[a,b]=await Promise.all([apiFetch<{data:Galaxy[]}>("/api/v1/universe/galaxies"),apiFetch<{data:World[]}>("/api/v1/universe/worlds")]);setG(a.data||[]);setW(b.data||[])}catch(e){setError(e instanceof Error?e.message:"UNIVERSE_LOAD_FAILED")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function createGalaxy(e:FormEvent){e.preventDefault();setBusy(true);try{await apiFetch("/api/v1/universe/galaxies",{method:"POST",body:JSON.stringify({name:gn,slug:gs})});setGn("");setGs("");await load()}catch(e){setError(e instanceof Error?e.message:"GALAXY_CREATE_FAILED")}finally{setBusy(false)}}
 async function createWorld(e:FormEvent){e.preventDefault();setBusy(true);try{await apiFetch("/api/v1/universe/worlds",{method:"POST",body:JSON.stringify({galaxy_id:galaxyId,name:wn,slug:ws,world_type:worldType})});setWn("");setWs("");await load()}catch(e){setError(e instanceof Error?e.message:"WORLD_CREATE_FAILED")}finally{setBusy(false)}}
 async function publish(id:string){setBusy(true);try{await apiFetch("/api/v1/universe/worlds/"+id+"/publish",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"WORLD_PUBLISH_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl"><header className="flex justify-between gap-4"><div><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 17</p><h1 className="mt-2 text-4xl font-semibold">AI Universe</h1><p className="mt-3 max-w-3xl text-slate-400">Galaxies, Worlds, Agent presence and spatial relationships backed by authoritative PostgreSQL state.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Refresh</button></header>{error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2">
 <section className="space-y-6"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Create Galaxy</h2><form onSubmit={createGalaxy} className="mt-4 grid gap-3"><input value={gn} onChange={e=>setGn(e.target.value)} placeholder="Galaxy name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={gs} onChange={e=>setGs(e.target.value)} placeholder="galaxy-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><button disabled={busy} className="rounded-xl bg-white px-4 py-3 text-sm text-black">Create Galaxy</button></form></div>
 <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Galaxies</h2>{g.length===0?<p className="mt-4 text-sm text-slate-500">{loading?"Loading…":"No galaxies exist."}</p>:<div className="mt-4 space-y-2">{g.map(x=><div key={x.id} className="rounded-xl border border-white/10 p-3"><div className="flex justify-between"><span>{x.name}</span><span className="text-xs uppercase text-slate-500">{x.status}</span></div><p className="mt-1 text-xs text-slate-500">{x.slug}</p></div>)}</div>}</div></section>
 <section className="space-y-6"><div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Create World</h2><form onSubmit={createWorld} className="mt-4 grid gap-3"><select value={galaxyId} onChange={e=>setGalaxyId(e.target.value)} required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">Select owned galaxy</option>{g.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input value={wn} onChange={e=>setWn(e.target.value)} placeholder="World name" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={ws} onChange={e=>setWs(e.target.value)} placeholder="world-slug" required className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><select value={worldType} onChange={e=>setWorldType(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm">{["social","interest","community","creator","enterprise","event","private"].map(x=><option key={x}>{x}</option>)}</select><button disabled={busy||!galaxyId} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Create World</button></form></div>
 <div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Worlds</h2>{w.length===0?<p className="mt-4 text-sm text-slate-500">No worlds exist.</p>:<div className="mt-4 space-y-2">{w.map(x=><button key={x.id} onClick={()=>setSel(x)} className="w-full rounded-xl border border-white/10 p-4 text-left"><div className="flex justify-between"><span>{x.name}</span><span className="text-xs uppercase text-slate-500">{x.status}</span></div><p className="mt-1 text-xs text-slate-500">{x.world_type} · {x.visibility}</p></button>)}</div>}</div>
 {sel&&<div className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">{sel.name}</h2><p className="mt-2 break-all text-xs text-slate-500">{sel.id}</p><button onClick={()=>void publish(sel.id)} disabled={busy||sel.status!=="draft"} className="mt-4 rounded-xl border border-white/10 px-4 py-2 text-sm disabled:opacity-40">Publish World</button></div>}</section></div></div></main>
}