"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../lib/api";
type State={id:string;status:string;world_id:string|null;theme_id:string|null;theme_version_id:string|null;world_template_id:string|null;scene_schema:Record<string,unknown>};
export default function WorldBuilderSurface(){
 const[states,setStates]=useState<State[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const[worldId,setWorldId]=useState(""),[themeId,setThemeId]=useState(""),[themeVersionId,setThemeVersionId]=useState(""),[templateId,setTemplateId]=useState(""),[schema,setSchema]=useState('{"world":"","theme":"","zones":[],"objects":[],"events":[],"spawn_points":[],"rules":{}}');
 async function load(){setLoading(true);setError(null);try{const r=await apiFetch<{data:State[]}>("/api/v1/world-builder");setStates(r.data||[])}catch(e){setError(e instanceof Error?e.message:"WORLD_BUILDER_LOAD_FAILED")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError(null);try{const scene_schema=JSON.parse(schema);await apiFetch("/api/v1/world-builder",{method:"POST",body:JSON.stringify({world_id:worldId||null,theme_id:themeId||null,theme_version_id:themeVersionId||null,world_template_id:templateId||null,scene_schema})});await load()}catch(e){setError(e instanceof Error?e.message:"WORLD_BUILDER_SAVE_FAILED")}finally{setBusy(false)}}
 async function validate(id:string){setBusy(true);setError(null);try{await apiFetch("/api/v1/world-builder/"+id+"/validate",{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"WORLD_BUILDER_VALIDATE_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-5 sm:p-9"><div className="mx-auto max-w-7xl"><header><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 21</p><h1 className="mt-2 text-4xl font-semibold">World Builder</h1><p className="mt-3 max-w-3xl text-slate-400">Persistent, owner-scoped scene builder state with deterministic schema validation. It does not grant World or Agent authority.</p></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Save Builder State</h2><form onSubmit={save} className="mt-4 grid gap-3"><input value={worldId} onChange={e=>setWorldId(e.target.value)} placeholder="World UUID (optional)" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={themeId} onChange={e=>setThemeId(e.target.value)} placeholder="Theme UUID (optional)" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={themeVersionId} onChange={e=>setThemeVersionId(e.target.value)} placeholder="Theme version UUID (optional)" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><input value={templateId} onChange={e=>setTemplateId(e.target.value)} placeholder="World template UUID (optional)" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><textarea value={schema} onChange={e=>setSchema(e.target.value)} rows={12} className="rounded-xl border border-white/10 bg-black/20 p-3 font-mono text-xs"/><button disabled={busy} className="rounded-xl bg-white px-4 py-3 text-sm text-black disabled:opacity-40">Save builder state</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">My Builder States</h2><button onClick={()=>void load()} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Refresh</button></div>{states.length===0?<p className="mt-4 text-sm text-slate-500">{loading?"Loading…":"No builder states yet."}</p>:<div className="mt-4 space-y-2">{states.map(s=><article key={s.id} className="rounded-xl border border-white/10 p-4"><div className="flex justify-between"><span>{s.status}</span><span className="text-xs text-slate-500">{s.id}</span></div><p className="mt-1 text-xs text-slate-500">World: {s.world_id||"not attached"} · Theme: {s.theme_id||"not selected"}</p>{s.status==="draft"&&<button disabled={busy} onClick={()=>void validate(s.id)} className="mt-3 rounded-lg border border-white/10 px-3 py-2 text-xs">Validate schema</button>}</article>)}</div>}</section></div></div></main>
}