"use client";
import {FormEvent,useEffect,useState} from "react";
import {apiFetch} from "../../../lib/api";

type Theme={id:string;name:string;slug:string;category:string;source:string;status:string;catalog_key:string|null};
type Template={id:string;name:string;slug:string;category:string;source:string;status:string;catalog_key:string|null};
type State={id:string;status:string;theme_id:string|null;theme_version_id:string|null;world_template_id:string|null;world_template_version_id:string|null;scene_schema:Record<string,unknown>;validation_report:Record<string,unknown>;performance_report:Record<string,unknown>;accessibility_report:Record<string,unknown>};

export default function Page(){
 const[themes,setThemes]=useState<Theme[]>([]),[templates,setTemplates]=useState<Template[]>([]),[states,setStates]=useState<State[]>([]);
 const[theme,setTheme]=useState(""),[template,setTemplate]=useState(""),[scene,setScene]=useState('{"environment":{},"lighting":{},"zones":[],"camera":{},"characters":[]}'),[selected,setSelected]=useState<State|null>(null);
 const[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[error,setError]=useState("");
 async function load(){const[a,b,c]=await Promise.all([apiFetch<{data:Theme[]}>("/api/v1/themes?source=platform"),apiFetch<{data:Template[]}>("/api/v1/themes/world-templates?source=platform"),apiFetch<{data:State[]}>("/api/v1/world-builder")]);setThemes(a.data||[]);setTemplates(b.data||[]);setStates(c.data||[])}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMsg("");try{const r=await apiFetch<{data:State}>("/api/v1/world-builder",{method:"POST",body:JSON.stringify({theme_id:theme||null,world_template_id:template||null,scene_schema:JSON.parse(scene)})});setSelected(r.data);setMsg("World Builder state tersimpan.");await load()}catch(e){setError(e instanceof Error?e.message:"WORLD_BUILDER_SAVE_FAILED")}finally{setBusy(false)}}
 async function action(path:string){if(!selected)return;setBusy(true);setError("");try{const r=await apiFetch<{data:State}>(`/api/v1/world-builder/${selected.id}/${path}`,{method:"POST"});if(r.data)setSelected(r.data);setMsg(path==="validate"?"Validation selesai.":"World Builder state dikirim.");await load()}catch(e){setError(e instanceof Error?e.message:"WORLD_BUILDER_ACTION_FAILED")}finally{setBusy(false)}}
 return <main className="min-h-screen p-6 sm:p-10"><div className="mx-auto max-w-7xl"><header><p className="text-xs uppercase tracking-[.25em] text-cyan-300">Phase 21 · Theme & World Builder</p><h1 className="mt-2 text-4xl font-semibold">Create Your World</h1><p className="mt-3 max-w-4xl text-slate-400">Human dapat memilih Theme + World Template, mengubah declarative scene, memvalidasi performance/accessibility, lalu submit melalui canonical World Builder. Renderer, authority boundary, security dan performance guardrails tetap dikunci.</p></header>
 {error&&<div className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}{msg&&<div className="mt-5 rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-sm text-emerald-200">{msg}</div>}
 <div className="mt-7 grid gap-6 lg:grid-cols-[1fr_1fr]"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">World Composition</h2><form onSubmit={save} className="mt-4 grid gap-3"><select value={theme} onChange={e=>setTheme(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">No platform theme</option>{themes.map(x=><option key={x.id} value={x.id}>{x.name} · {x.category}</option>)}</select><select value={template} onChange={e=>setTemplate(e.target.value)} className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"><option value="">No platform world template</option>{templates.map(x=><option key={x.id} value={x.id}>{x.name} · {x.category}</option>)}</select><textarea value={scene} onChange={e=>setScene(e.target.value)} className="min-h-[360px] rounded-xl border border-white/10 bg-black/20 p-4 font-mono text-xs"/><button disabled={busy} className="rounded-xl bg-white px-4 py-3 text-sm font-medium text-black disabled:opacity-40">Save Builder State</button></form></section>
 <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Builder Guardrails</h2><div className="mt-4 space-y-3 text-sm text-slate-400"><div className="rounded-xl border border-white/10 p-4"><b className="text-white">Editable</b><p className="mt-1">Environment, architecture, lighting, atmosphere, materials, characters, zones, spawn points, camera, animation.</p></div><div className="rounded-xl border border-white/10 p-4"><b className="text-white">Locked</b><p className="mt-1">Authority boundary, renderer, security and performance budget. Theme presentation cannot grant permission or ownership.</p></div><div className="rounded-xl border border-white/10 p-4"><b className="text-white">Runtime chain</b><p className="mt-1">Theme Template → World Template → World Builder State → AllphaWorldRenderer.</p></div>{selected&&<div className="rounded-xl border border-cyan-300/20 bg-cyan-300/5 p-4"><p>Status: {selected.status}</p><p className="mt-1">Validation: {JSON.stringify(selected.validation_report)}</p><p className="mt-1">Performance: {JSON.stringify(selected.performance_report)}</p><div className="mt-4 flex gap-2"><button disabled={busy} onClick={()=>void action("validate")} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Validate</button><button disabled={busy} onClick={()=>void action("submit")} className="rounded-lg bg-cyan-300 px-3 py-2 text-xs text-black">Submit</button></div></div>}</div><h2 className="mt-7 font-semibold">My Builder States</h2><div className="mt-3 space-y-2">{states.length===0?<p className="text-xs text-slate-500">Belum ada state. Tidak ada seed user data.</p>:states.map(s=><button key={s.id} onClick={()=>setSelected(s)} className={`block w-full rounded-xl border p-3 text-left text-xs ${selected?.id===s.id?"border-cyan-300/40":"border-white/10"}`}><span>{s.status}</span><span className="ml-3 text-slate-500">{s.id}</span></button>)}</div></section></div></div></main>
}