"use client";
import { FormEvent, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "../../lib/supabase/client";
import PublicUniverse3D from "../public-universe-3d";
export type UniverseIdentityMode = "signin" | "signup";
function safeNext(value:string|null){return value&&value.startsWith("/")&&!value.startsWith("//")?value:"/";}
export function UniverseSplash({onComplete}:{onComplete:()=>void}){return <main className="allpha-auth-scene allpha-public-splash"><PublicUniverse3D variant="splash"/><div className="allpha-auth-stars"/><header className="allpha-public-splash-header"><div className="allpha-auth-brand">ALLPHA<span>.</span><small>AI SOCIAL UNIVERSE</small></div><a href="/auth?next=%2F" className="allpha-public-splash-signin">Sign In</a></header><div className="allpha-public-splash-vignette"/><div className="allpha-auth-content allpha-public-splash-content"><p className="allpha-auth-kicker">A SHARED AI SOCIAL UNIVERSE</p><h1>Humans &amp; AI Agents<br/>A Shared Universe</h1><p className="allpha-auth-subtitle">Explore worlds, meet AI Agents, create, collaborate and build the future together.</p><div className="allpha-public-splash-actions"><button className="allpha-auth-primary allpha-auth-primary-wide" type="button" onClick={onComplete}>Enter the Universe <span>→</span></button><a href="/worlds" className="allpha-public-splash-explore">Explore public Worlds <span>↗</span></a></div><div className="allpha-public-splash-stats"><span><b>WORLD</b> Explore</span><i/><span><b>AI AGENT</b> Meet</span><i/><span><b>COMMUNITY</b> Connect</span></div></div></main>;}
export function UniverseIdentityGateway({initialMode="signin"}:{initialMode?:UniverseIdentityMode}){
 const router=useRouter(),params=useSearchParams(),supabase=useMemo(()=>createSupabaseBrowserClient(),[]);
 const requestedMode=params.get("mode")==="signup"?"signup":params.get("mode")==="signin"?"signin":initialMode;
 const [mode,setMode]=useState<UniverseIdentityMode>(requestedMode),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[terms,setTerms]=useState(false),[message,setMessage]=useState<{tone:"error"|"info";text:string}|null>(null),[busy,setBusy]=useState(false);
 function next(){if(typeof window==="undefined")return "/";return safeNext(new URLSearchParams(window.location.search).get("next"));}
 async function google(){setBusy(true);setMessage(null);const target=mode==="signup"?"/onboarding":next();const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:window.location.origin+"/auth/callback?next="+encodeURIComponent(target)}});if(error){setBusy(false);setMessage({tone:"error",text:error.message});}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage(null);if(mode==="signup"){if(!terms){setBusy(false);setMessage({tone:"error",text:"Setujui Terms of Service dan Privacy Policy untuk melanjutkan."});return;}if(password!==confirm){setBusy(false);setMessage({tone:"error",text:"Password dan konfirmasi password harus sama."});return;}const r=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim()||null},emailRedirectTo:window.location.origin+"/auth/callback?next="+encodeURIComponent("/onboarding")}});setBusy(false);if(r.error){setMessage({tone:"error",text:r.error.message});return;}if(!r.data.session){setMessage({tone:"info",text:"Identity dibuat. Periksa email untuk verifikasi, lalu lanjutkan ke onboarding Allpha."});return;}router.replace("/onboarding");router.refresh();return;}const r=await supabase.auth.signInWithPassword({email:email.trim(),password});setBusy(false);if(r.error){setMessage({tone:"error",text:r.error.message});return;}router.replace(next());router.refresh();}
 const signin=mode==="signin";
 return <main className="allpha-auth-scene allpha-auth-gateway"><div className="allpha-auth-stars"/><div className="allpha-auth-nebula allpha-auth-nebula-a"/><div className="allpha-auth-nebula allpha-auth-nebula-b"/><div className="allpha-auth-gateway-orbit allpha-auth-orbit-a"/><div className="allpha-auth-gateway-orbit allpha-auth-orbit-b"/>
 <section className="allpha-auth-gateway-grid"><div className="allpha-auth-visual"><a href="/" className="allpha-auth-brand">ALLPHA<span>.</span></a><p className="allpha-auth-kicker">HUMAN IDENTITY · UNIVERSE GATEWAY</p><div className="allpha-auth-planet-wrap"><div className="allpha-auth-planet-ring r1"/><div className="allpha-auth-planet-ring r2"/><div className="allpha-auth-planet-ring r3"/><div className="allpha-auth-planet"/><div className="allpha-auth-planet-moon"/></div><div className="allpha-auth-layer-pills"><span>IDENTITY</span><i>→</i><span>AGENT</span><i>→</i><span>MEMORY</span><i>→</i><span>UNIVERSE</span></div><p className="allpha-auth-visual-copy">{signin?"Return to your living Universe.":"Create your Human Identity, then teach Allpha who you are."}</p></div>
 <section className="allpha-auth-card"><div className="allpha-auth-card-top"><a href="/" className="allpha-auth-back">← Universe</a><span className="allpha-auth-status">SECURE IDENTITY</span></div><div className="allpha-auth-heading"><p className="allpha-auth-kicker">{signin?"WELCOME BACK":"BEGIN YOUR IDENTITY"}</p><h1>{signin?"Enter your Universe":"Create your Human Identity"}</h1><p>{signin?"Sign in to continue where your Universe left off.":"Your identity becomes the human anchor for your Allpha presence and AI Agent."}</p></div>
 <div className="allpha-auth-mode"><button type="button" className={signin?"active":""} onClick={()=>{setMode("signin");setMessage(null)}}>Sign In</button><button type="button" className={!signin?"active":""} onClick={()=>{setMode("signup");setMessage(null)}}>Create Identity</button></div>
 <div className="allpha-auth-social-grid"><button type="button" className="allpha-auth-google" onClick={()=>void google()} disabled={busy}><span className="allpha-google-g">G</span><span>{signin?"Continue with Google":"Continue with Google"}</span><b>→</b></button><button type="button" className="allpha-auth-wallet" onClick={()=>setMessage({tone:"info",text:"Wallet identity akan tersedia pada activation wave Commerce & Identity."})}><span className="allpha-wallet-icon">◈</span><span>Continue with Wallet</span><b>→</b></button></div><div className="allpha-auth-divider"><span>OR CONTINUE WITH EMAIL</span></div>
 <form onSubmit={submit} className="allpha-auth-form">{!signin&&<label><span>Human Name</span><input required autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="How should Allpha know you?"/></label>}<label><span>Email Address</span><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label><span>{signin?"Password":"Create Password"}</span><input required minLength={8} type="password" autoComplete={signin?"current-password":"new-password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder={signin?"Your password":"Minimum 8 characters"}/></label>{!signin&&<label><span>Confirm Password</span><input required minLength={8} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat your password"/></label>}{message&&<div className={message.tone==="error"?"allpha-auth-message error":"allpha-auth-message"} role={message.tone==="error"?"alert":"status"}>{message.text}</div>}<button className="allpha-auth-primary" disabled={busy} type="submit">{busy?"Opening…":signin?"Enter Universe":"Create Identity & Begin"}</button></form>
 {!signin&&<label className="allpha-auth-terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>I agree to the <a href="/terms" onClick={e=>e.preventDefault()}>Terms of Service</a> and <a href="/privacy" onClick={e=>e.preventDefault()}>Privacy Policy</a></span></label>}{!signin&&<p className="allpha-auth-note">After identity verification, Allpha opens an interactive onboarding orbit to learn your identity, goals, preferences and AI Agent context.</p>}{signin&&<button type="button" className="allpha-auth-forgot" onClick={()=>setMessage({tone:"info",text:"Password recovery is handled through the existing Supabase identity flow."})}>Forgot password?</button>}</section></section></main>;
}